# Generated by Django 4.2.2 on 2023-07-10 18:11

import basvurular.models
import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Duyuru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=255)),
                ('icerik', ckeditor.fields.RichTextField()),
                ('tarih', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Duyurular',
            },
        ),
        migrations.CreateModel(
            name='EvrakPass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=100)),
                ('soyisim', models.CharField(max_length=100)),
                ('pasaportno', models.CharField(max_length=100)),
                ('numara', models.CharField(max_length=100)),
                ('operator', models.CharField(max_length=100)),
                ('gececegi_operator', models.CharField(max_length=100)),
                ('irtibat', models.CharField(max_length=100)),
                ('adres', models.TextField()),
                ('pass1', models.ImageField(blank=True, upload_to=basvurular.models.generate_filename)),
                ('pass2', models.ImageField(blank=True, upload_to=basvurular.models.generate_filename)),
                ('ikametgah', models.FileField(blank=True, upload_to=basvurular.models.generate_filename)),
                ('tarih', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Passaportlu işlemler',
            },
        ),
        migrations.CreateModel(
            name='Modemlimi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': '82. Modem Bilgisi',
            },
        ),
        migrations.CreateModel(
            name='Operatorleri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Operatorleri ADSL',
            },
        ),
        migrations.CreateModel(
            name='SebekeiciTurkTarife',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'SebekeiciTurkTarife',
            },
        ),
        migrations.CreateModel(
            name='SebekeiciYabanciTarife',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'SebekeiciYabanciTarife',
            },
        ),
        migrations.CreateModel(
            name='Telefon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': '81. Telefon Bilgisi',
                'ordering': ['ad'],
            },
        ),
        migrations.CreateModel(
            name='TurkTarife',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': '2. MNT Turk Tarifeler',
                'ordering': ['ad'],
            },
        ),
        migrations.CreateModel(
            name='YabanciTarife',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': '1. MNT YabanciTarifeler',
            },
        ),
        migrations.CreateModel(
            name='YeniFaturaliTurkTarife',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Yeni Faturalı Turk Tarifeler',
            },
        ),
        migrations.CreateModel(
            name='YeniFaturaliYabanciTarife',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Yeni Faturalı Yabanci Tarifeler',
            },
        ),
        migrations.CreateModel(
            name='YeniTurkTarife',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Yeni Kontorlu Turk Tarifeler',
            },
        ),
        migrations.CreateModel(
            name='YeniYabanciTarife',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'YeniKontorlu Yabanci Tarifeler',
            },
        ),
        migrations.CreateModel(
            name='Sebekeici',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kimlik_tipi', models.CharField(max_length=10)),
                ('isim', models.CharField(max_length=255)),
                ('soyisim', models.CharField(max_length=255)),
                ('tc', models.CharField(max_length=100)),
                ('numara', models.CharField(max_length=100)),
                ('irtibat', models.CharField(max_length=100)),
                ('operatoru', models.CharField(max_length=100)),
                ('aks', models.CharField(max_length=255)),
                ('adres', models.CharField(max_length=255)),
                ('kimlik_on', models.ImageField(blank=True, null=True, upload_to='evrak/')),
                ('kimlik_arka', models.ImageField(blank=True, null=True, upload_to='evrak/')),
                ('ikametgah', models.FileField(blank=True, null=True, upload_to='evrak/')),
                ('tarih', models.DateTimeField(auto_now_add=True)),
                ('tarifeTurk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sebeke_ici_turk', to='basvurular.sebekeiciturktarife')),
                ('tarifeYabanci', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sebeke_ici_yabanci', to='basvurular.sebekeiciyabancitarife')),
            ],
            options={
                'verbose_name_plural': 'Şebeke içi işlemler',
            },
        ),
        migrations.CreateModel(
            name='OperatorTarifeleri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=255)),
                ('operatoru', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='OperatorTarifeleri', to='basvurular.operatorleri')),
            ],
            options={
                'verbose_name_plural': 'ADSL Operator Tarifeleri',
            },
        ),
        migrations.CreateModel(
            name='KontorluYeniHat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kimlik_tipi', models.CharField(max_length=10)),
                ('isim', models.CharField(max_length=255)),
                ('soyisim', models.CharField(max_length=255)),
                ('tc', models.CharField(max_length=100)),
                ('irtibat', models.CharField(max_length=100)),
                ('operatoru', models.CharField(max_length=100)),
                ('aks', models.CharField(max_length=255)),
                ('simno', models.CharField(max_length=100)),
                ('adres', models.CharField(max_length=255)),
                ('kimlik_on', models.ImageField(blank=True, null=True, upload_to='evrak/')),
                ('kimlik_arka', models.ImageField(blank=True, null=True, upload_to='evrak/')),
                ('tarih', models.DateTimeField(auto_now_add=True)),
                ('tarifeTurk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='yeni_kontorlu_evrak_turk', to='basvurular.yeniturktarife')),
                ('tarifeYabanci', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='yeni_kontorlu_evrak_yabanci', to='basvurular.yeniyabancitarife')),
            ],
            options={
                'verbose_name_plural': 'Kontörlü Yeni Hat',
            },
        ),
        migrations.CreateModel(
            name='internet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kimlik_tipi', models.CharField(max_length=10)),
                ('isim', models.CharField(max_length=255)),
                ('soyisim', models.CharField(max_length=255)),
                ('tc', models.CharField(max_length=100)),
                ('irtibat', models.CharField(max_length=100)),
                ('aks', models.CharField(max_length=255)),
                ('adres', models.CharField(max_length=255)),
                ('kimlik_on', models.ImageField(blank=True, null=True, upload_to='evrak/')),
                ('kimlik_arka', models.ImageField(blank=True, null=True, upload_to='evrak/')),
                ('ikametgah', models.FileField(blank=True, null=True, upload_to='evrak/')),
                ('tarih', models.DateTimeField(auto_now_add=True)),
                ('Operatorler', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Operatorleri', to='basvurular.operatorleri')),
                ('modemolsunmu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ModemDurumu', to='basvurular.modemlimi')),
                ('operatortarife', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='OperatorTarifeleri', to='basvurular.operatortarifeleri')),
                ('sabithat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SabitHat', to='basvurular.telefon')),
            ],
            options={
                'verbose_name_plural': '80. ADSL Başvuru Kayıtları',
            },
        ),
        migrations.CreateModel(
            name='FaturaliYeniHat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kimlik_tipi', models.CharField(max_length=10)),
                ('isim', models.CharField(max_length=255)),
                ('soyisim', models.CharField(max_length=255)),
                ('tc', models.CharField(max_length=100)),
                ('irtibat', models.CharField(max_length=100)),
                ('operatoru', models.CharField(max_length=100)),
                ('aks', models.CharField(max_length=255)),
                ('simno', models.CharField(max_length=100)),
                ('adres', models.CharField(max_length=255)),
                ('kimlik_on', models.ImageField(blank=True, null=True, upload_to='evrak/')),
                ('kimlik_arka', models.ImageField(blank=True, null=True, upload_to='evrak/')),
                ('ikametgah', models.FileField(blank=True, null=True, upload_to='evrak/')),
                ('tarih', models.DateTimeField(auto_now_add=True)),
                ('tarifeTurk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='yeni_faturali_evrak_turk', to='basvurular.yenifaturaliturktarife')),
                ('tarifeYabanci', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='yeni_faturali_evrak_yabanci', to='basvurular.yenifaturaliyabancitarife')),
            ],
            options={
                'verbose_name_plural': 'Faturalı Yeni Hat',
            },
        ),
        migrations.CreateModel(
            name='Evrak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kimlik_tipi', models.CharField(max_length=10)),
                ('isim', models.CharField(max_length=255)),
                ('soyisim', models.CharField(max_length=255)),
                ('tc', models.CharField(max_length=100)),
                ('numara', models.CharField(max_length=100)),
                ('irtibat', models.CharField(max_length=100)),
                ('operatoru', models.CharField(max_length=100)),
                ('gececegi_operator', models.CharField(max_length=100)),
                ('aks', models.CharField(max_length=255)),
                ('simno', models.CharField(max_length=100)),
                ('adres', models.CharField(max_length=255)),
                ('kimlik_on', models.ImageField(blank=True, null=True, upload_to='evrak/')),
                ('kimlik_arka', models.ImageField(blank=True, null=True, upload_to='evrak/')),
                ('ikametgah', models.FileField(blank=True, null=True, upload_to='evrak/')),
                ('tarih', models.DateTimeField(auto_now_add=True)),
                ('tarifeTurk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evrak_turk', to='basvurular.turktarife')),
                ('tarifeYabanci', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evrak_yabanci', to='basvurular.yabancitarife')),
            ],
            options={
                'verbose_name_plural': 'MNT',
            },
        ),
    ]
