# Generated by Django 4.2.2 on 2023-07-11 20:59

import basvurular.models
import ckeditor.fields
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('debt', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name_plural': '80. Bakiye işlemleri',
            },
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': '82. Bankalar',
            },
        ),
        migrations.CreateModel(
            name='Duyuru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=255)),
                ('icerik', ckeditor.fields.RichTextField()),
                ('tarih', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Duyurular',
            },
        ),
        migrations.CreateModel(
            name='Modemlimi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': '82. Modem Bilgisi',
            },
        ),
        migrations.CreateModel(
            name='Operatorleri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': '83. ADSL Operatorleri ',
            },
        ),
        migrations.CreateModel(
            name='SebekeiciTurkTarife',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=255)),
                ('operator', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': '42. SebekeiciTurkTarife',
            },
        ),
        migrations.CreateModel(
            name='SebekeiciYabanciTarife',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=255)),
                ('operator', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': '41. SebekeiciYabanciTarife',
            },
        ),
        migrations.CreateModel(
            name='Telefon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': '81. Telefon Bilgisi',
                'ordering': ['ad'],
            },
        ),
        migrations.CreateModel(
            name='TurkTarife',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=255)),
                ('operator', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': '12. MNT Turk Tarifeler',
                'ordering': ['ad'],
            },
        ),
        migrations.CreateModel(
            name='YabanciTarife',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=255)),
                ('operator', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': '11. MNT YabanciTarifeler',
            },
        ),
        migrations.CreateModel(
            name='YeniFaturaliTurkTarife',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=255)),
                ('operator', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': '32. Yeni Faturalı Turk Tarifeler',
            },
        ),
        migrations.CreateModel(
            name='YeniFaturaliYabanciTarife',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=255)),
                ('operator', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': '31. Yeni Faturalı Yabanci Tarifeler',
            },
        ),
        migrations.CreateModel(
            name='YeniTurkTarife',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=255)),
                ('operator', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': '22. Yeni Kontorlu Turk Tarifeler',
            },
        ),
        migrations.CreateModel(
            name='YeniYabanciTarife',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=255)),
                ('operator', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': '21. YeniKontorlu Yabanci Tarifeler',
            },
        ),
        migrations.CreateModel(
            name='Sebekeici',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kimlik_tipi', models.CharField(max_length=10)),
                ('isim', models.CharField(max_length=255)),
                ('soyisim', models.CharField(max_length=255)),
                ('tc', models.CharField(max_length=100)),
                ('numara', models.CharField(max_length=100)),
                ('irtibat', models.CharField(max_length=100)),
                ('operatoru', models.CharField(max_length=100)),
                ('aks', models.CharField(max_length=255)),
                ('adres', models.CharField(max_length=255)),
                ('kimlik_on', models.ImageField(blank=True, null=True, upload_to='evrak/')),
                ('kimlik_arka', models.ImageField(blank=True, null=True, upload_to='evrak/')),
                ('ikametgah', models.FileField(blank=True, null=True, upload_to='evrak/')),
                ('aktivasyon_durumu', models.CharField(blank=True, choices=[('Beklemede', 'Beklemede'), ('İşlemde', 'İşlemde'), ('Eksik Evrak', 'Eksik Evrak'), ('Aktif', 'Aktif'), ('Hatalı', 'Hatalı')], default='Beklemede', max_length=20, null=True)),
                ('odeme_durumu', models.CharField(blank=True, choices=[('OdemeYapilmadi', 'OdemeYapilmadi'), ('OdemeYapildi', 'OdemeYapildi'), ('Hatalı', 'Hatalı')], default='OdemeYapilmadi', max_length=20, null=True)),
                ('BayiAciklama', models.CharField(blank=True, max_length=255, null=True)),
                ('GizliAciklama', models.TextField(blank=True, null=True)),
                ('tutar', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True)),
                ('tarih', models.DateTimeField(auto_now_add=True)),
                ('tarifeTurk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sebeke_ici_turk', to='basvurular.sebekeiciturktarife')),
                ('tarifeYabanci', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sebeke_ici_yabanci', to='basvurular.sebekeiciyabancitarife')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '40. Şebeke içi işlemler Başvuru Kayıtları',
            },
        ),
        migrations.CreateModel(
            name='OperatorTarifeleri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=255)),
                ('operatoru', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='OperatorTarifeleri', to='basvurular.operatorleri')),
            ],
            options={
                'verbose_name_plural': '84. ADSL Operator Tarifeleri',
            },
        ),
        migrations.CreateModel(
            name='KontorluYeniHat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kimlik_tipi', models.CharField(max_length=10)),
                ('isim', models.CharField(max_length=255)),
                ('soyisim', models.CharField(max_length=255)),
                ('tc', models.CharField(max_length=100)),
                ('irtibat', models.CharField(max_length=100)),
                ('operatoru', models.CharField(max_length=100)),
                ('aks', models.CharField(max_length=255)),
                ('simno', models.CharField(max_length=100)),
                ('adres', models.CharField(max_length=255)),
                ('kimlik_on', models.ImageField(blank=True, null=True, upload_to='evrak/')),
                ('kimlik_arka', models.ImageField(blank=True, null=True, upload_to='evrak/')),
                ('aktivasyon_durumu', models.CharField(blank=True, choices=[('Beklemede', 'Beklemede'), ('İşlemde', 'İşlemde'), ('Eksik Evrak', 'Eksik Evrak'), ('Aktif', 'Aktif'), ('Hatalı', 'Hatalı')], default='Beklemede', max_length=20, null=True)),
                ('odeme_durumu', models.CharField(blank=True, choices=[('OdemeYapilmadi', 'OdemeYapilmadi'), ('OdemeYapildi', 'OdemeYapildi'), ('Hatalı', 'Hatalı')], default='OdemeYapilmadi', max_length=20, null=True)),
                ('BayiAciklama', models.CharField(blank=True, max_length=255, null=True)),
                ('GizliAciklama', models.TextField(blank=True, null=True)),
                ('tutar', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True)),
                ('tarih', models.DateTimeField(auto_now_add=True)),
                ('tarifeTurk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='yeni_kontorlu_evrak_turk', to='basvurular.yeniturktarife')),
                ('tarifeYabanci', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='yeni_kontorlu_evrak_yabanci', to='basvurular.yeniyabancitarife')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '20. Kontörlü Yeni Hat Başvuru Kayıtları',
            },
        ),
        migrations.CreateModel(
            name='internet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kimlik_tipi', models.CharField(max_length=10)),
                ('isim', models.CharField(max_length=255)),
                ('soyisim', models.CharField(max_length=255)),
                ('tc', models.CharField(max_length=100)),
                ('irtibat', models.CharField(max_length=100)),
                ('aks', models.CharField(max_length=255)),
                ('adres', models.CharField(max_length=255)),
                ('kimlik_on', models.ImageField(blank=True, null=True, upload_to='evrak/')),
                ('kimlik_arka', models.ImageField(blank=True, null=True, upload_to='evrak/')),
                ('ikametgah', models.FileField(blank=True, null=True, upload_to='evrak/')),
                ('aktivasyon_durumu', models.CharField(blank=True, choices=[('Beklemede', 'Beklemede'), ('İşlemde', 'İşlemde'), ('Eksik Evrak', 'Eksik Evrak'), ('Aktif', 'Aktif'), ('Hatalı', 'Hatalı')], default='Beklemede', max_length=20, null=True)),
                ('odeme_durumu', models.CharField(blank=True, choices=[('OdemeYapilmadi', 'OdemeYapilmadi'), ('OdemeYapildi', 'OdemeYapildi'), ('Hatalı', 'Hatalı')], default='OdemeYapilmadi', max_length=20, null=True)),
                ('BayiAciklama', models.CharField(blank=True, max_length=255, null=True)),
                ('GizliAciklama', models.TextField(blank=True, null=True)),
                ('tutar', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True)),
                ('tarih', models.DateTimeField(auto_now_add=True)),
                ('Operatorler', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Operatorleri', to='basvurular.operatorleri')),
                ('modemolsunmu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ModemDurumu', to='basvurular.modemlimi')),
                ('operatortarife', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='OperatorTarifeleri', to='basvurular.operatortarifeleri')),
                ('sabithat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SabitHat', to='basvurular.telefon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '80. ADSL Başvuru Kayıtları',
            },
        ),
        migrations.CreateModel(
            name='FaturaliYeniHat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kimlik_tipi', models.CharField(max_length=10)),
                ('isim', models.CharField(max_length=255)),
                ('soyisim', models.CharField(max_length=255)),
                ('tc', models.CharField(max_length=100)),
                ('irtibat', models.CharField(max_length=100)),
                ('operatoru', models.CharField(max_length=100)),
                ('aks', models.CharField(max_length=255)),
                ('simno', models.CharField(max_length=100)),
                ('adres', models.CharField(max_length=255)),
                ('kimlik_on', models.ImageField(blank=True, null=True, upload_to='evrak/')),
                ('kimlik_arka', models.ImageField(blank=True, null=True, upload_to='evrak/')),
                ('ikametgah', models.FileField(blank=True, null=True, upload_to='evrak/')),
                ('aktivasyon_durumu', models.CharField(blank=True, choices=[('Beklemede', 'Beklemede'), ('İşlemde', 'İşlemde'), ('Eksik Evrak', 'Eksik Evrak'), ('Aktif', 'Aktif'), ('Hatalı', 'Hatalı')], default='Beklemede', max_length=20, null=True)),
                ('odeme_durumu', models.CharField(blank=True, choices=[('OdemeYapilmadi', 'OdemeYapilmadi'), ('OdemeYapildi', 'OdemeYapildi'), ('Hatalı', 'Hatalı')], default='OdemeYapilmadi', max_length=20, null=True)),
                ('BayiAciklama', models.CharField(blank=True, max_length=255, null=True)),
                ('GizliAciklama', models.TextField(blank=True, null=True)),
                ('tutar', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True)),
                ('tarih', models.DateTimeField(auto_now_add=True)),
                ('tarifeTurk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='yeni_faturali_evrak_turk', to='basvurular.yenifaturaliturktarife')),
                ('tarifeYabanci', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='yeni_faturali_evrak_yabanci', to='basvurular.yenifaturaliyabancitarife')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '30. Faturalı Yeni Hat Başvuru Kayıtları',
            },
        ),
        migrations.CreateModel(
            name='EvrakPass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=100)),
                ('soyisim', models.CharField(max_length=100)),
                ('pasaportno', models.CharField(max_length=100)),
                ('numara', models.CharField(max_length=100)),
                ('operator', models.CharField(max_length=100)),
                ('gececegi_operator', models.CharField(max_length=100)),
                ('irtibat', models.CharField(max_length=100)),
                ('adres', models.TextField()),
                ('pass1', models.ImageField(blank=True, upload_to=basvurular.models.generate_filename)),
                ('pass2', models.ImageField(blank=True, upload_to=basvurular.models.generate_filename)),
                ('ikametgah', models.FileField(blank=True, upload_to=basvurular.models.generate_filename)),
                ('aktivasyon_durumu', models.CharField(blank=True, choices=[('Beklemede', 'Beklemede'), ('İşlemde', 'İşlemde'), ('Eksik Evrak', 'Eksik Evrak'), ('Aktif', 'Aktif'), ('Hatalı', 'Hatalı')], default='Beklemede', max_length=20, null=True)),
                ('odeme_durumu', models.CharField(blank=True, choices=[('OdemeYapilmadi', 'OdemeYapilmadi'), ('OdemeYapildi', 'OdemeYapildi'), ('Hatalı', 'Hatalı')], default='OdemeYapilmadi', max_length=20, null=True)),
                ('BayiAciklama', models.CharField(blank=True, max_length=255, null=True)),
                ('GizliAciklama', models.TextField(blank=True, null=True)),
                ('tutar', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True)),
                ('tarih', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '50. Passaportlu işlemler Başvuru Kayıtları',
            },
        ),
        migrations.CreateModel(
            name='Evrak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kimlik_tipi', models.CharField(max_length=10)),
                ('isim', models.CharField(max_length=255)),
                ('soyisim', models.CharField(max_length=255)),
                ('tc', models.CharField(max_length=100)),
                ('numara', models.CharField(max_length=100)),
                ('irtibat', models.CharField(max_length=100)),
                ('operatoru', models.CharField(max_length=100)),
                ('gececegi_operator', models.CharField(max_length=100)),
                ('aks', models.CharField(max_length=255)),
                ('simno', models.CharField(max_length=100)),
                ('adres', models.CharField(max_length=255)),
                ('kimlik_on', models.ImageField(blank=True, null=True, upload_to='evrak/')),
                ('kimlik_arka', models.ImageField(blank=True, null=True, upload_to='evrak/')),
                ('ikametgah', models.FileField(blank=True, null=True, upload_to='evrak/')),
                ('aktivasyon_durumu', models.CharField(blank=True, choices=[('Beklemede', 'Beklemede'), ('İşlemde', 'İşlemde'), ('Eksik Evrak', 'Eksik Evrak'), ('Aktif', 'Aktif'), ('Hatalı', 'Hatalı')], default='Beklemede', max_length=20, null=True)),
                ('odeme_durumu', models.CharField(blank=True, choices=[('OdemeYapilmadi', 'OdemeYapilmadi'), ('OdemeYapildi', 'OdemeYapildi'), ('Hatalı', 'Hatalı')], default='OdemeYapilmadi', max_length=20, null=True)),
                ('BayiAciklama', models.CharField(blank=True, max_length=255, null=True)),
                ('GizliAciklama', models.TextField(blank=True, null=True)),
                ('tutar', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True)),
                ('tarih', models.DateTimeField(auto_now_add=True)),
                ('tarifeTurk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evrak_turk', to='basvurular.turktarife')),
                ('tarifeYabanci', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evrak_yabanci', to='basvurular.yabancitarife')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '10. MNT Başvuru Kayıtları',
            },
        ),
        migrations.CreateModel(
            name='BalanceTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('balance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basvurular.balance')),
            ],
            options={
                'verbose_name_plural': '81. Bakiye Hareketleri',
            },
        ),
        migrations.AddField(
            model_name='balance',
            name='bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basvurular.bank'),
        ),
        migrations.AddField(
            model_name='balance',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
