# Generated by Django 4.2.2 on 2023-07-12 07:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('basvurular', '0003_bakiyehareketleri_banka_bayi_listesi_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiyatGuruplari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FiyatKategorisi', models.CharField(blank=True, max_length=255, null=True)),
                ('OzelApi', models.BooleanField(default=False, verbose_name='OzelApiYapilsin mi ?')),
            ],
            options={
                'verbose_name': 'Fiyat Guruplari',
                'verbose_name_plural': 'Fiyat Guruplari',
            },
        ),
        migrations.AddField(
            model_name='bayi_listesi',
            name='aciklama',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='kontorluyenihat',
            name='simimei',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='SimCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.CharField(blank=True, max_length=100, null=True)),
                ('imei', models.CharField(max_length=15)),
                ('status', models.CharField(choices=[('used', 'Kullanıldı'), ('pending', 'Beklemede')], default='pending', max_length=20)),
                ('dist_status', models.CharField(choices=[('calculated', 'Hesaplandı'), ('pending', 'Beklemede')], default='pending', max_length=20)),
                ('bayi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Fiyatlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Operatoru', models.CharField(blank=True, max_length=255, null=True)),
                ('Hat', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('fiyat_grubu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='basvurular.fiyatguruplari')),
            ],
        ),
        migrations.AddField(
            model_name='bakiyehareketleri',
            name='Fiyati',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='basvurular.fiyatguruplari'),
        ),
    ]
