# Generated by Django 4.2.2 on 2023-07-11 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basvurular', '0004_alter_evrak_tutar_alter_evrakpass_tutar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sebekeiciturktarife',
            name='operator',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sebekeiciyabancitarife',
            name='operator',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='turktarife',
            name='operator',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='yabancitarife',
            name='operator',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='yenifaturaliturktarife',
            name='operator',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='yenifaturaliyabancitarife',
            name='operator',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
