# Generated by Django 4.2.2 on 2023-07-12 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basvurular', '0005_remove_evrak_simno_remove_kontorluyenihat_simno_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faturaliyenihat',
            name='simno',
        ),
        migrations.RemoveField(
            model_name='fiyatguruplari',
            name='OzelApi',
        ),
        migrations.AddField(
            model_name='faturaliyenihat',
            name='simimei',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bayi_listesi',
            name='islem_durumu',
            field=models.CharField(choices=[('islem_sec', 'işlem Türünü Seç'), ('nakit_ekle', 'Nakit/Havele/EFT Bakiye Ekle'), ('borc_ve_bakiye_ekle', 'Hem Borç Hem Bakiye Ekle'), ('bakiye_dus', 'Bakiye Düş'), ('sadece_borc_ekle', 'Sadece Borç Ekle'), ('borc_dus_bakiye_ekle', 'Borç Düş Bakiye Ekle')], default='islem_sec', max_length=20),
        ),
    ]
