# Generated by Django 4.2.2 on 2023-07-12 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basvurular', '0006_remove_faturaliyenihat_simno_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiyatKategorisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategori_adi', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Urun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urun_adi', models.CharField(max_length=255)),
                ('urun_fiyati', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fiyat_kategorisi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basvurular.fiyatkategorisi')),
            ],
        ),
        migrations.DeleteModel(
            name='Fiyatlar',
        ),
        migrations.AlterField(
            model_name='bakiyehareketleri',
            name='Fiyati',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='basvurular.fiyatkategorisi'),
        ),
        migrations.DeleteModel(
            name='FiyatGuruplari',
        ),
    ]
