# Generated by Django 4.2.2 on 2023-07-12 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basvurular', '0007_fiyatkategorisi_urun_delete_fiyatlar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bakiyehareketleri',
            name='Fiyati',
        ),
        migrations.AddField(
            model_name='bayi_listesi',
            name='Fiyati',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='basvurular.fiyatkategorisi'),
        ),
    ]
