# Generated by Django 4.2.2 on 2023-07-12 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basvurular', '0008_remove_bakiyehareketleri_fiyati_bayi_listesi_fiyati'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evrak',
            name='operatoru',
        ),
    ]
