# Generated by Django 5.2.17 on 2026-10-09 21:27

import apps.magaza.models
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("katalog", "0016_kategorialani_tarifeler"),
        ("magaza", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Kategori",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "olusturma_tarihi",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturma Tarihi"
                    ),
                ),
                (
                    "guncelleme_tarihi",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncelleme Tarihi"
                    ),
                ),
                ("ad", models.CharField(max_length=80, unique=True, verbose_name="Ad")),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=90, unique=True, verbose_name="Kısa Ad"
                    ),
                ),
                ("sira", models.PositiveIntegerField(default=0, verbose_name="Sıra")),
                ("aktif", models.BooleanField(default=True, verbose_name="Aktif")),
            ],
            options={
                "verbose_name": "Fatura Kategorisi",
                "verbose_name_plural": "Fatura Kategorileri",
                "ordering": ["sira", "ad"],
            },
        ),
        migrations.CreateModel(
            name="Robot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "olusturma_tarihi",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturma Tarihi"
                    ),
                ),
                (
                    "guncelleme_tarihi",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncelleme Tarihi"
                    ),
                ),
                (
                    "ad",
                    models.CharField(
                        help_text="ev-laptop, server-1…",
                        max_length=60,
                        unique=True,
                        verbose_name="Ad",
                    ),
                ),
                (
                    "anahtar_ozeti",
                    models.CharField(blank=True, editable=False, max_length=64),
                ),
                ("aktif", models.BooleanField(default=True, verbose_name="Aktif")),
                (
                    "son_nabiz",
                    models.DateTimeField(
                        blank=True, editable=False, null=True, verbose_name="Son Nabız"
                    ),
                ),
                (
                    "mesgul",
                    models.BooleanField(
                        default=False, editable=False, verbose_name="Meşgul"
                    ),
                ),
                (
                    "oturum_canli",
                    models.BooleanField(
                        default=True, editable=False, verbose_name="Oturum Canlı"
                    ),
                ),
            ],
            options={
                "verbose_name": "Sorgu Robotu",
                "verbose_name_plural": "Sorgu Robotları",
                "ordering": ["ad"],
            },
        ),
        migrations.CreateModel(
            name="Kurum",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "olusturma_tarihi",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturma Tarihi"
                    ),
                ),
                (
                    "guncelleme_tarihi",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncelleme Tarihi"
                    ),
                ),
                (
                    "kod",
                    models.CharField(
                        help_text="Robotun bu kurumu tanıdığı tekil kod (vodafone, turkcell…). Değiştirme.",
                        max_length=80,
                        unique=True,
                        verbose_name="Robot Kodu",
                    ),
                ),
                ("ad", models.CharField(max_length=120, verbose_name="Kurum Adı")),
                (
                    "sorgulu",
                    models.BooleanField(
                        default=True,
                        help_text="Açıksa bayi numarayı yazınca fatura sorgulanır, çıkan faturalardan seçip öder. Kapalıysa (HGS 100 TL gibi) sorgu yoktur; bayi aşağıdaki sabit fiyatı öder.",
                        verbose_name="Sorgulu",
                    ),
                ),
                (
                    "alan_etiketi",
                    models.CharField(
                        default="Abone No",
                        help_text="Bayinin formunda kutunun üstünde yazar: Telefon Numarası, Abone No, Plaka…",
                        max_length=60,
                        verbose_name="Numara Alanının Adı",
                    ),
                ),
                (
                    "min_hane",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="En Az Hane"
                    ),
                ),
                (
                    "max_hane",
                    models.PositiveSmallIntegerField(
                        default=20, verbose_name="En Çok Hane"
                    ),
                ),
                (
                    "sadece_rakam",
                    models.BooleanField(
                        default=True,
                        help_text="Açıksa numaraya harf yazılamaz (telefon, abone no). Plakada kapalı.",
                        verbose_name="Yalnızca Rakam",
                    ),
                ),
                (
                    "aciklama",
                    models.CharField(
                        blank=True,
                        help_text="Formun altında yazar: “Başında 0 olmadan yazın” gibi.",
                        max_length=255,
                        verbose_name="Bayiye Açıklama",
                    ),
                ),
                (
                    "hizmet_bedeli",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Sorgulu kurumda bayiden her fatura için sağlayıcı tutarına eklenir; bizim kârımızdır. 0 ise bayi sağlayıcının tutarını aynen öder.",
                        max_digits=10,
                        verbose_name="Hizmet Bedeli (fatura başına)",
                    ),
                ),
                (
                    "tavsiye_ek",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Sorgulu kurumda bayinin müşteriden ayrıca alması önerilen tutar; bayinin kârıdır. Ekranda müşteri fiyatı = bayinin ödediği + bu.",
                        max_digits=10,
                        verbose_name="Müşteriden Ek (fatura başına)",
                    ),
                ),
                (
                    "bayi_fiyati",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Sorgusuz kurumda bayinin ödeyeceği tutar. Boşsa bayiye görünmez.",
                        max_digits=10,
                        null=True,
                        verbose_name="Bayi Fiyatı",
                    ),
                ),
                (
                    "tavsiye_fiyati",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Sorgusuz kurumda bayinin müşteriye söyleyeceği fiyat (tavsiye).",
                        max_digits=10,
                        null=True,
                        verbose_name="Müşteri Fiyatı",
                    ),
                ),
                (
                    "alis_fiyati",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Sorgusuz kurumda sağlayıcıya ödediğimiz; yalnızca kâr hesabı için.",
                        max_digits=10,
                        null=True,
                        verbose_name="Alışımız",
                    ),
                ),
                ("sira", models.PositiveIntegerField(default=0, verbose_name="Sıra")),
                ("aktif", models.BooleanField(default=True, verbose_name="Aktif")),
                (
                    "kategori",
                    models.ForeignKey(
                        blank=True,
                        help_text="Boşsa bayi ekranında “Diğer” altında durur.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="kurumlar",
                        to="fatura.kategori",
                        verbose_name="Kategori",
                    ),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        blank=True,
                        help_text="Seçilirse kartta operatörün marka rengi görünür.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fatura_kurumlari",
                        to="katalog.operator",
                        verbose_name="Operatör",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fatura Kurumu",
                "verbose_name_plural": "Fatura Kurumları",
                "ordering": ["sira", "ad"],
            },
        ),
        migrations.CreateModel(
            name="Sorgu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "olusturma_tarihi",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturma Tarihi"
                    ),
                ),
                (
                    "guncelleme_tarihi",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncelleme Tarihi"
                    ),
                ),
                (
                    "referans_no",
                    models.CharField(
                        default=apps.magaza.models.referans_no_uret,
                        editable=False,
                        max_length=12,
                        unique=True,
                        verbose_name="Referans No",
                    ),
                ),
                ("numara", models.CharField(max_length=40, verbose_name="Numara")),
                (
                    "durum",
                    models.CharField(
                        choices=[
                            ("bekliyor", "Sırada"),
                            ("sorgulaniyor", "Sorgulanıyor"),
                            ("tamam", "Tamamlandı"),
                            ("hata", "Sorgulanamadı"),
                        ],
                        default="bekliyor",
                        max_length=20,
                        verbose_name="Durum",
                    ),
                ),
                (
                    "alinma_tarihi",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Robot Aldı"
                    ),
                ),
                (
                    "sonuc_tarihi",
                    models.DateTimeField(blank=True, null=True, verbose_name="Sonuç"),
                ),
                (
                    "sonuc",
                    models.JSONField(blank=True, default=dict, verbose_name="Sonuç"),
                ),
                (
                    "mesaj",
                    models.CharField(blank=True, max_length=255, verbose_name="Mesaj"),
                ),
                (
                    "bayi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fatura_sorgulari",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Bayi",
                    ),
                ),
                (
                    "kurum",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sorgular",
                        to="fatura.kurum",
                        verbose_name="Kurum",
                    ),
                ),
                (
                    "robot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sorgular",
                        to="fatura.robot",
                        verbose_name="Robot",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fatura Sorgusu",
                "verbose_name_plural": "Fatura Sorguları",
                "ordering": ["-olusturma_tarihi"],
            },
        ),
        migrations.CreateModel(
            name="Odeme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "olusturma_tarihi",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturma Tarihi"
                    ),
                ),
                (
                    "guncelleme_tarihi",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncelleme Tarihi"
                    ),
                ),
                ("kurum_adi", models.CharField(max_length=120, verbose_name="Kurum")),
                ("numara", models.CharField(max_length=40, verbose_name="Numara")),
                (
                    "abone_adi",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Abone Adı"
                    ),
                ),
                (
                    "faturalar",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Ödenen faturalar: fatura no, son ödeme, sağlayıcı tutarı, bayinin ödediği.",
                        verbose_name="Faturalar",
                    ),
                ),
                (
                    "saglayici_tutari",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Yönetimin sağlayıcıda ödeyeceği toplam (sorgusuzda alışımız).",
                        max_digits=12,
                        null=True,
                        verbose_name="Sağlayıcıya Ödenecek",
                    ),
                ),
                (
                    "hizmet_bedeli",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Hizmet Bedeli",
                    ),
                ),
                (
                    "tavsiye_fiyati",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Bayinin o gün gördüğü tavsiye; oran sonra değişse de kayıtta kalır.",
                        max_digits=12,
                        null=True,
                        verbose_name="Müşteri Fiyatı",
                    ),
                ),
                (
                    "durum",
                    models.CharField(
                        choices=[
                            ("bekliyor", "Ödeniyor"),
                            ("odendi", "Ödendi"),
                            ("iptal", "İptal edildi"),
                        ],
                        default="bekliyor",
                        max_length=20,
                        verbose_name="Durum",
                    ),
                ),
                (
                    "sonuc_notu",
                    models.CharField(
                        blank=True,
                        help_text="Bayi görür: iptal sebebi, dekont no…",
                        max_length=255,
                        verbose_name="Yönetim Notu",
                    ),
                ),
                (
                    "karar_tarihi",
                    models.DateTimeField(blank=True, null=True, verbose_name="Karar"),
                ),
                (
                    "bayi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fatura_odemeleri",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Bayi",
                    ),
                ),
                (
                    "karar_veren",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Karar Veren",
                    ),
                ),
                (
                    "kurum",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="odemeler",
                        to="fatura.kurum",
                        verbose_name="Kurum",
                    ),
                ),
                (
                    "siparis",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fatura",
                        to="magaza.siparis",
                        verbose_name="Sipariş",
                    ),
                ),
                (
                    "sorgu",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="odemeler",
                        to="fatura.sorgu",
                        verbose_name="Sorgu",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fatura Ödemesi",
                "verbose_name_plural": "Fatura Ödemeleri",
                "ordering": ["-olusturma_tarihi"],
            },
        ),
        migrations.AddIndex(
            model_name="sorgu",
            index=models.Index(
                fields=["durum", "olusturma_tarihi"],
                name="fatura_sorg_durum_a4c7dc_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="sorgu",
            index=models.Index(
                fields=["bayi", "-olusturma_tarihi"],
                name="fatura_sorg_bayi_id_ecff88_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="odeme",
            index=models.Index(
                fields=["durum", "-olusturma_tarihi"],
                name="fatura_odem_durum_455d25_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="odeme",
            index=models.Index(
                fields=["bayi", "-olusturma_tarihi"],
                name="fatura_odem_bayi_id_b198c3_idx",
            ),
        ),
    ]
