# Generated by Django 5.2.17 on 2026-10-09 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fatura", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="robot",
            name="mesai_baslangic",
            field=models.TimeField(
                blank=True, editable=False, null=True, verbose_name="Mesai Başlangıcı"
            ),
        ),
        migrations.AddField(
            model_name="robot",
            name="mesai_bitis",
            field=models.TimeField(
                blank=True, editable=False, null=True, verbose_name="Mesai Bitişi"
            ),
        ),
    ]
