# Generated by Django 5.2.17 on 2026-10-10 06:21

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fatura", "0002_robot_mesai"),
        ("kontor", "0022_kategori_tam_kontor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kurum",
            name="bayi_fiyati",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Sorgusuz kurumda grubuna ayrı fiyat yazılmamış bayinin ödeyeceği. İkisi de boşsa kalem o bayiye görünmez.",
                max_digits=10,
                null=True,
                verbose_name="Genel Bayi Fiyatı",
            ),
        ),
        migrations.AlterField(
            model_name="kurum",
            name="hizmet_bedeli",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Sorgulu kurumda bayi her fatura için sağlayıcının toplamı + bunu öder; grubuna ayrı rakam yazılmamışsa. 0 ise sağlayıcının tutarını aynen öder.",
                max_digits=10,
                verbose_name="Genel Hizmet Bedeli (fatura başına)",
            ),
        ),
        migrations.AlterField(
            model_name="kurum",
            name="tavsiye_ek",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Sorgulu kurumda müşteri fiyatı = sağlayıcının toplamı + bu. Bayinin kazancı müşteri fiyatıyla kendi ödediği arasındaki farktır.",
                max_digits=10,
                verbose_name="Müşteriden Ek (fatura başına)",
            ),
        ),
        migrations.CreateModel(
            name="GrupFiyati",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tutar",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Tutar"
                    ),
                ),
                (
                    "grup",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fatura_fiyatlari",
                        to="kontor.fiyatgrubu",
                        verbose_name="Fiyat Grubu",
                    ),
                ),
                (
                    "kurum",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grup_fiyatlari",
                        to="fatura.kurum",
                        verbose_name="Kurum",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fatura Grup Fiyatı",
                "verbose_name_plural": "Fatura Grup Fiyatları",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("kurum", "grup"), name="fatura_grup_fiyati_tekil"
                    )
                ],
            },
        ),
    ]
