# Generated by Django 5.2.17 on 2026-10-10 06:36

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fatura", "0004_tek_tavsiye_alani"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kurum",
            name="bayi_fiyati",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Yalnızca fiyat grubu yokken: sorgusuz kalemde bayinin ödeyeceği. Gruplar varsa grubun sayfasından girilir.",
                max_digits=10,
                null=True,
                verbose_name="Bayi Fiyatı",
            ),
        ),
        migrations.AlterField(
            model_name="kurum",
            name="hizmet_bedeli",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Yalnızca fiyat grubu yokken: sorgulu kurumda bayi sağlayıcının toplamı + bunu öder. Gruplar varsa grubun sayfasından girilir.",
                max_digits=10,
                verbose_name="Hizmet Bedeli (fatura başına)",
            ),
        ),
    ]
