# Generated by Django 5.2.17 on 2026-10-10 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fatura", "0005_alan_aciklamalari"),
        ("kontor", "0023_fiyat_grubu_adi"),
    ]

    operations = [
        migrations.CreateModel(
            name="FaturaFiyatGrubu",
            fields=[],
            options={
                "verbose_name": "Fiyat Grubu",
                "verbose_name_plural": "Fiyat Grupları",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("kontor.fiyatgrubu",),
        ),
    ]
