# Generated by Django 5.2.17 on 2026-10-10 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fatura", "0006_fiyat_grubu_vekili"),
    ]

    operations = [
        migrations.AddField(
            model_name="robot",
            name="paket_sorgusu",
            field=models.BooleanField(
                default=False, editable=False, verbose_name="Paket Sorgusu"
            ),
        ),
    ]
