# Generated by Django 5.2.17 on 2026-10-10 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fatura", "0007_robot_paket_sorgusu"),
        ("kontor", "0025_gorulen_paket_hesabi"),
    ]

    operations = [
        migrations.AddField(
            model_name="robot",
            name="saglayici",
            field=models.ForeignKey(
                blank=True,
                help_text="Robotun giriş yaptığı bayi paneli hangi sağlayıcının (Kontorbizde)? Paket sorgusunda görülen kodlar ve alışlar o hesabındır: Kataloğa ekle yeni paketi bu sağlayıcıya kodu ve alışıyla bağlar, yükleme onun API'sine gider.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="robotlar",
                to="kontor.saglayici",
                verbose_name="Hesabı",
            ),
        ),
    ]
