# Generated by Django 5.2.17 on 2026-10-10 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fatura", "0008_robot_saglayici"),
    ]

    operations = [
        migrations.RemoveField(model_name="robot", name="saglayici",),
    ]
