# Generated by Django 5.2.17 on 2026-10-10 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fatura", "0009_remove_robot_saglayici"),
    ]

    operations = [
        migrations.AlterField(
            model_name="odeme",
            name="saglayici_tutari",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Sorgulu kurumda faturaların bedeli (sağlayıcının kendi işlem bedeli hariç); sorgusuz kalemde alışımız.",
                max_digits=12,
                null=True,
                verbose_name="Sağlayıcıya Ödenecek",
            ),
        ),
    ]
