version: "3.8"
services:
  postgres:
    container_name: postgres-fadil
    hostname: postgres-fadil
    image: postgres:latest
    env_file:
      - aktivasyon/docker.env
    ports:
      - "5434:5432"
    volumes:
      - "postgresql-data-fadil:/var/lib/postgresql/data"
    networks:
      - main_fadil
    command: -p 5434
  app:
    container_name: app_fadil
    hostname: app_fadil
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - aktivasyon/docker.env
    volumes:
      - static-data-fadil:/srv/public
      - .:/srv/app_fadil
    expose:
      - 8002
    depends_on:
      - postgres-fadil
    command: gunicorn aktivasyon.wsgi:application --bind 0.0.0.0:8002
    networks:
      - main_fadil
      - bridge_network

networks:
  main_fadil:
  bridge_network:
    name: nginx_network
    driver: bridge

volumes:
  postgresql-data-fadil:
  static-data-fadil: