# Generated by Django 5.2.17 on 2026-09-11 21:11

import apps.esim.saglayicilar
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("magaza", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Saglayici",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "olusturma_tarihi",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturma Tarihi"
                    ),
                ),
                (
                    "guncelleme_tarihi",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncelleme Tarihi"
                    ),
                ),
                (
                    "ad",
                    models.CharField(max_length=100, unique=True, verbose_name="Ad"),
                ),
                (
                    "tur",
                    models.CharField(
                        choices=apps.esim.saglayicilar.saglayici_secenekleri,
                        help_text="Hangi API ile konuşulacağı. Yeni bir sağlayıcı türü yazılımla eklenir.",
                        max_length=30,
                        verbose_name="Sağlayıcı",
                    ),
                ),
                (
                    "erisim_kodu",
                    models.CharField(
                        help_text="Sağlayıcının panelinden alınan API anahtarı (AccessCode).",
                        max_length=200,
                        verbose_name="Erişim Kodu",
                    ),
                ),
                (
                    "gizli_anahtar",
                    models.CharField(
                        blank=True,
                        help_text="Varsa istekler bununla imzalanır (SecretKey). Boş bırakılabilir.",
                        max_length=200,
                        verbose_name="Gizli Anahtar",
                    ),
                ),
                (
                    "varsayilan_kar_orani",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("50.00"),
                        help_text="Bu sağlayıcıdan ilk kez gelen paketlere uygulanır. Var olan paketin oranı değişmez; toplu değiştirmek için paket listesindeki işlemi kullanın.",
                        max_digits=6,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Varsayılan Kâr Oranı (%)",
                    ),
                ),
                (
                    "aktif",
                    models.BooleanField(
                        default=True,
                        help_text="Kapatılırsa bu sağlayıcının hiçbir paketi satılmaz, kayıtlar durur.",
                        verbose_name="Aktif",
                    ),
                ),
                (
                    "son_esitleme",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        null=True,
                        verbose_name="Son Eşitleme",
                    ),
                ),
                (
                    "son_bakiye_usd",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        editable=False,
                        max_digits=12,
                        null=True,
                        verbose_name="Sağlayıcıdaki Bakiye ($)",
                    ),
                ),
                (
                    "son_bakiye_tarihi",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
            ],
            options={
                "verbose_name": "eSIM Sağlayıcısı",
                "verbose_name_plural": "eSIM Sağlayıcıları",
                "ordering": ["ad"],
            },
        ),
        migrations.CreateModel(
            name="Ulke",
            fields=[
                (
                    "kod",
                    models.CharField(
                        max_length=2,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ISO Kodu",
                    ),
                ),
                ("ad", models.CharField(max_length=100, verbose_name="Ad")),
                (
                    "aktif",
                    models.BooleanField(
                        default=True,
                        help_text="Kapatılırsa bu ülkenin paketleri bayiye gösterilmez.",
                        verbose_name="Aktif",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ülke",
                "verbose_name_plural": "Ülkeler",
                "ordering": ["ad"],
            },
        ),
        migrations.CreateModel(
            name="Paket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "olusturma_tarihi",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturma Tarihi"
                    ),
                ),
                (
                    "guncelleme_tarihi",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncelleme Tarihi"
                    ),
                ),
                ("kod", models.CharField(max_length=50, verbose_name="Paket Kodu")),
                (
                    "slug",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="Sağlayıcı Kısa Adı"
                    ),
                ),
                ("ad", models.CharField(max_length=200, verbose_name="Ad")),
                ("aciklama", models.TextField(blank=True, verbose_name="Açıklama")),
                (
                    "kapsam",
                    models.CharField(
                        help_text="Ülke kodları, sıralı ve virgüllü. Aynı kapsamdaki paketler karşılaştırılır.",
                        max_length=800,
                        verbose_name="Kapsam",
                    ),
                ),
                (
                    "ulke_sayisi",
                    models.PositiveIntegerField(default=1, verbose_name="Ülke Sayısı"),
                ),
                ("hacim_bayt", models.BigIntegerField(verbose_name="Hacim (bayt)")),
                ("sure_gun", models.PositiveIntegerField(verbose_name="Süre (gün)")),
                (
                    "hiz",
                    models.CharField(blank=True, max_length=30, verbose_name="Hız"),
                ),
                (
                    "operatorler",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Operatörler"
                    ),
                ),
                (
                    "alis_usd",
                    models.DecimalField(
                        decimal_places=4, max_digits=10, verbose_name="Alış ($)"
                    ),
                ),
                (
                    "kar_orani",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Alışın üzerine eklenecek yüzde. 88 → alış × 1,88.",
                        max_digits=6,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Kâr Oranı (%)",
                    ),
                ),
                ("aktif", models.BooleanField(default=True, verbose_name="Aktif")),
                (
                    "saglayicida_var",
                    models.BooleanField(
                        default=True,
                        editable=False,
                        help_text="Son eşitlemede sağlayıcının listesinde bulunmayan paket satılmaz.",
                        verbose_name="Sağlayıcıda Var",
                    ),
                ),
                (
                    "son_gorulme",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        null=True,
                        verbose_name="Son Görülme",
                    ),
                ),
                (
                    "saglayici",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paketler",
                        to="esim.saglayici",
                        verbose_name="Sağlayıcı",
                    ),
                ),
                (
                    "ulkeler",
                    models.ManyToManyField(
                        related_name="paketler", to="esim.ulke", verbose_name="Ülkeler"
                    ),
                ),
            ],
            options={
                "verbose_name": "eSIM Paketi",
                "verbose_name_plural": "eSIM Paketleri",
                "ordering": ["kapsam", "hacim_bayt", "sure_gun", "alis_usd"],
            },
        ),
        migrations.CreateModel(
            name="Teslimat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "olusturma_tarihi",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturma Tarihi"
                    ),
                ),
                (
                    "guncelleme_tarihi",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncelleme Tarihi"
                    ),
                ),
                (
                    "paket_kodu",
                    models.CharField(max_length=50, verbose_name="Paket Kodu"),
                ),
                (
                    "islem_no",
                    models.CharField(
                        help_text="Sağlayıcıya gönderilen tekil anahtar; aynı anahtar ikinci sipariş açmaz.",
                        max_length=50,
                        unique=True,
                        verbose_name="İşlem No",
                    ),
                ),
                (
                    "saglayici_siparis_no",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Sağlayıcı Sipariş No"
                    ),
                ),
                (
                    "esim_no",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Sağlayıcı eSIM No"
                    ),
                ),
                (
                    "iccid",
                    models.CharField(blank=True, max_length=30, verbose_name="ICCID"),
                ),
                (
                    "ac",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Aktivasyon Kodu (LPA)"
                    ),
                ),
                ("qr_url", models.URLField(blank=True, verbose_name="QR Görseli")),
                ("kisa_url", models.URLField(blank=True, verbose_name="Kısa Bağlantı")),
                (
                    "apn",
                    models.CharField(blank=True, max_length=60, verbose_name="APN"),
                ),
                (
                    "durum",
                    models.CharField(
                        choices=[
                            ("bekliyor", "Sağlayıcıya iletiliyor"),
                            ("hazirlaniyor", "Profil hazırlanıyor"),
                            ("hazir", "Hazır"),
                            ("iptal", "İptal edildi"),
                            ("hata", "Hata"),
                        ],
                        default="bekliyor",
                        max_length=20,
                        verbose_name="Durum",
                    ),
                ),
                ("hata", models.TextField(blank=True, verbose_name="Hata")),
                (
                    "alis_usd",
                    models.DecimalField(
                        decimal_places=4, max_digits=10, verbose_name="Alış ($)"
                    ),
                ),
                (
                    "kur",
                    models.DecimalField(
                        decimal_places=4, max_digits=10, verbose_name="Kur"
                    ),
                ),
                (
                    "alis_tl",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Alış (₺)"
                    ),
                ),
                (
                    "son_sorgu",
                    models.DateTimeField(
                        blank=True, editable=False, null=True, verbose_name="Son Sorgu"
                    ),
                ),
                (
                    "paket",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="teslimatlar",
                        to="esim.paket",
                        verbose_name="Paket",
                    ),
                ),
                (
                    "saglayici",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="teslimatlar",
                        to="esim.saglayici",
                        verbose_name="Sağlayıcı",
                    ),
                ),
                (
                    "siparis",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="esim",
                        to="magaza.siparis",
                        verbose_name="Sipariş",
                    ),
                ),
            ],
            options={
                "verbose_name": "eSIM Teslimatı",
                "verbose_name_plural": "eSIM Teslimatları",
                "ordering": ["-olusturma_tarihi"],
            },
        ),
        migrations.AddIndex(
            model_name="paket",
            index=models.Index(
                fields=["aktif", "saglayicida_var"], name="esim_paket_aktif_47378f_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="paket",
            constraint=models.UniqueConstraint(
                fields=("saglayici", "kod"), name="esim_paket_saglayici_kod"
            ),
        ),
    ]
