# Generated by Django 5.2.17 on 2026-09-11 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("esim", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="paket",
            options={
                "ordering": [
                    "ulke_sayisi",
                    "kapsam",
                    "hacim_bayt",
                    "sure_gun",
                    "alis_usd",
                ],
                "verbose_name": "eSIM Paketi",
                "verbose_name_plural": "eSIM Paketleri",
            },
        ),
    ]
