# Generated by Django 5.2.17 on 2026-09-11 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("esim", "0002_paket_siralamasi"),
    ]

    operations = [
        migrations.AddField(
            model_name="saglayici",
            name="oturum_anahtari",
            field=models.TextField(
                blank=True, editable=False, verbose_name="Oturum Jetonu"
            ),
        ),
        migrations.AddField(
            model_name="saglayici",
            name="oturum_bitis",
            field=models.DateTimeField(
                blank=True, editable=False, null=True, verbose_name="Jeton Bitişi"
            ),
        ),
    ]
