# Generated by Django 5.2.17 on 2026-09-11 21:36

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("esim", "0003_saglayici_oturum"),
    ]

    operations = [
        migrations.AddField(
            model_name="teslimat",
            name="kar_orani",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Sipariş anında bayinin grubundan ya da paketten alınan oran.",
                max_digits=6,
                verbose_name="Uygulanan Kâr Oranı (%)",
            ),
        ),
    ]
