# Generated by Django 5.2.17 on 2026-09-11 21:41

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("esim", "0004_teslimat_kar_orani"),
    ]

    operations = [
        migrations.AddField(
            model_name="teslimat",
            name="tavsiye_fiyati",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Sipariş anında bayiye gösterilen “müşteriye şu fiyata sat” rakamı; 0 ise gösterilmedi.",
                max_digits=12,
                verbose_name="Tavsiye Edilen Satış (₺)",
            ),
        ),
    ]
