# Generated by Django 5.2.17 on 2026-09-11 21:46

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("esim", "0005_teslimat_tavsiye_fiyati"),
        ("magaza", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="teslimat",
            name="musteri_adi",
            field=models.CharField(
                blank=True, max_length=120, verbose_name="Müşteri Adı"
            ),
        ),
        migrations.AddField(
            model_name="teslimat",
            name="musteri_telefonu",
            field=models.CharField(
                blank=True, max_length=30, verbose_name="Müşteri Telefonu"
            ),
        ),
        migrations.CreateModel(
            name="Yukleme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "olusturma_tarihi",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturma Tarihi"
                    ),
                ),
                (
                    "guncelleme_tarihi",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncelleme Tarihi"
                    ),
                ),
                (
                    "paket_kodu",
                    models.CharField(max_length=50, verbose_name="Yükleme Paketi Kodu"),
                ),
                ("paket_adi", models.CharField(max_length=200, verbose_name="Paket")),
                (
                    "hacim_bayt",
                    models.BigIntegerField(default=0, verbose_name="Hacim (bayt)"),
                ),
                (
                    "sure_gun",
                    models.PositiveIntegerField(default=0, verbose_name="Süre (gün)"),
                ),
                (
                    "islem_no",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="İşlem No"
                    ),
                ),
                (
                    "saglayici_yukleme_no",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Sağlayıcı Yükleme No"
                    ),
                ),
                (
                    "durum",
                    models.CharField(
                        choices=[
                            ("bekliyor", "Sağlayıcıya iletiliyor"),
                            ("tamam", "Yüklendi"),
                            ("hata", "Hata"),
                            ("iptal", "İptal edildi"),
                        ],
                        default="bekliyor",
                        max_length=20,
                        verbose_name="Durum",
                    ),
                ),
                ("hata", models.TextField(blank=True, verbose_name="Hata")),
                (
                    "alis_usd",
                    models.DecimalField(
                        decimal_places=4, max_digits=10, verbose_name="Alış ($)"
                    ),
                ),
                (
                    "kur",
                    models.DecimalField(
                        decimal_places=4, max_digits=10, verbose_name="Kur"
                    ),
                ),
                (
                    "alis_tl",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Alış (₺)"
                    ),
                ),
                (
                    "kar_orani",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=6,
                        verbose_name="Uygulanan Kâr Oranı (%)",
                    ),
                ),
                (
                    "toplam_hacim_bayt",
                    models.BigIntegerField(
                        default=0, verbose_name="Yükleme Sonrası Toplam Hacim"
                    ),
                ),
                (
                    "son_kullanma",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="Yeni Son Kullanma"
                    ),
                ),
                (
                    "siparis",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="esim_yukleme",
                        to="magaza.siparis",
                        verbose_name="Sipariş",
                    ),
                ),
                (
                    "teslimat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="yuklemeler",
                        to="esim.teslimat",
                        verbose_name="eSIM",
                    ),
                ),
            ],
            options={
                "verbose_name": "eSIM Yüklemesi",
                "verbose_name_plural": "eSIM Yüklemeleri",
                "ordering": ["-olusturma_tarihi"],
            },
        ),
    ]
