# Generated by Django 5.2.17 on 2026-09-11 22:12

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("esim", "0006_yukleme_ve_musteri"),
    ]

    operations = [
        migrations.AlterField(
            model_name="saglayici",
            name="varsayilan_kar_orani",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("50.00"),
                help_text="Bu sağlayıcıdan gelen paketlere uygulanır. Oranı değiştirip kaydedince hâlâ eski oranda duran paketler yeni orana geçer; elle farklı oran verilmiş paketler yerinde kalır (Paketler ekranından toplu değiştirilir).",
                max_digits=6,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Varsayılan Kâr Oranı (%)",
            ),
        ),
    ]
