# Generated by Django 5.2.17 on 2026-09-11 22:14

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("esim", "0007_varsayilan_oran_aciklamasi"),
    ]

    operations = [
        migrations.AlterField(
            model_name="saglayici",
            name="varsayilan_kar_orani",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("50.00"),
                help_text="Bu sağlayıcının paketlerine uygulanan kâr oranı. Eşitlemede yeni gelen paketlere yazılır; sonradan değiştirince listedeki “Fiyatları güncelle” düğmesi bütün paketleri bu orana çeker.",
                max_digits=6,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Varsayılan Kâr Oranı (%)",
            ),
        ),
    ]
