# Generated by Django 5.2.17 on 2026-09-11 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("esim", "0008_fiyat_guncelle_aciklamasi"),
    ]

    operations = [
        migrations.AddField(
            model_name="teslimat",
            name="grup_orani",
            field=models.IntegerField(
                blank=True,
                help_text="Sipariş anında bayi grubundan gelen fark; boşsa fark yoktu.",
                null=True,
                verbose_name="Uygulanan Grup Farkı (%)",
            ),
        ),
        migrations.AddField(
            model_name="yukleme",
            name="grup_orani",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Uygulanan Grup Farkı (%)"
            ),
        ),
    ]
