# Generated by Django 5.2.17 on 2026-09-11 22:55

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("esim", "0009_teslimat_grup_orani_yukleme_grup_orani"),
    ]

    operations = [
        migrations.AddField(
            model_name="yukleme",
            name="tavsiye_fiyati",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=12,
                verbose_name="Tavsiye Edilen Satış (₺)",
            ),
        ),
    ]
