# Generated by Django 5.2.17 on 2026-09-11 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("esim", "0010_yukleme_tavsiye"),
    ]

    operations = [
        migrations.AddField(
            model_name="teslimat",
            name="aktivasyon_zamani",
            field=models.CharField(
                blank=True, max_length=40, verbose_name="İlk Bağlantı"
            ),
        ),
        migrations.AddField(
            model_name="teslimat",
            name="eid",
            field=models.CharField(blank=True, max_length=40, verbose_name="Cihaz EID"),
        ),
        migrations.AddField(
            model_name="teslimat",
            name="esim_durumu",
            field=models.CharField(
                blank=True, max_length=30, verbose_name="Paket Durumu"
            ),
        ),
        migrations.AddField(
            model_name="teslimat",
            name="kurulum_durumu",
            field=models.CharField(
                blank=True, max_length=30, verbose_name="Profil Durumu (SM-DP+)"
            ),
        ),
        migrations.AddField(
            model_name="teslimat",
            name="son_durum_sorgusu",
            field=models.DateTimeField(
                blank=True, editable=False, null=True, verbose_name="Son Durum Sorgusu"
            ),
        ),
    ]
