# Generated by Django 5.2.17 on 2026-09-13 17:57

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("esim", "0011_kurulum_durumu"),
    ]

    operations = [
        migrations.RemoveField(model_name="teslimat", name="grup_orani",),
        migrations.RemoveField(model_name="yukleme", name="grup_orani",),
        migrations.AlterField(
            model_name="teslimat",
            name="tavsiye_fiyati",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Sipariş anında bayiye gösterilen “müşteriye şu fiyata sat” rakamı (bayi grubunun kârıyla); 0 ise gösterilmedi.",
                max_digits=12,
                verbose_name="Tavsiye Edilen Satış (₺)",
            ),
        ),
    ]
