# Generated by Django 5.2.17 on 2026-09-06 11:15

import apps.destek.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("basvurular", "0015_rename_ana_hakedis_basvuru_alis_bedeli_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DestekTalebi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "olusturma_tarihi",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturma Tarihi"
                    ),
                ),
                (
                    "guncelleme_tarihi",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncelleme Tarihi"
                    ),
                ),
                (
                    "referans_no",
                    models.CharField(
                        default=apps.destek.models.referans_no_uret,
                        editable=False,
                        max_length=10,
                        unique=True,
                        verbose_name="Talep No",
                    ),
                ),
                ("konu", models.CharField(max_length=150, verbose_name="Konu")),
                (
                    "durum",
                    models.CharField(
                        choices=[("acik", "Açık"), ("kapali", "Kapalı")],
                        default="acik",
                        max_length=20,
                        verbose_name="Durum",
                    ),
                ),
                (
                    "son_mesaj_tarihi",
                    models.DateTimeField(
                        blank=True, editable=False, null=True, verbose_name="Son Mesaj"
                    ),
                ),
                (
                    "yanit_bekliyor",
                    models.BooleanField(
                        default=True, editable=False, verbose_name="Yanıt Bekliyor"
                    ),
                ),
                (
                    "basvuru",
                    models.ForeignKey(
                        blank=True,
                        help_text="Talep bir başvuruyla ilgiliyse bağlanır; zorunlu değildir.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="destek_talepleri",
                        to="basvurular.basvuru",
                        verbose_name="İlgili Başvuru",
                    ),
                ),
                (
                    "bayi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="destek_talepleri",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Açan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Destek Talebi",
                "verbose_name_plural": "Destek Talepleri",
                "ordering": ["-son_mesaj_tarihi", "-olusturma_tarihi"],
            },
        ),
        migrations.CreateModel(
            name="DestekMesaji",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "personelden",
                    models.BooleanField(default=False, verbose_name="Yönetimden"),
                ),
                ("icerik", models.TextField(verbose_name="Mesaj")),
                (
                    "tarih",
                    models.DateTimeField(auto_now_add=True, verbose_name="Tarih"),
                ),
                (
                    "gonderen",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="destek_mesajlari",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Gönderen",
                    ),
                ),
                (
                    "talep",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mesajlar",
                        to="destek.destektalebi",
                        verbose_name="Talep",
                    ),
                ),
            ],
            options={
                "verbose_name": "Destek Mesajı",
                "verbose_name_plural": "Destek Mesajları",
                "ordering": ["tarih"],
            },
        ),
        migrations.AddIndex(
            model_name="destektalebi",
            index=models.Index(
                fields=["bayi", "-son_mesaj_tarihi"],
                name="destek_dest_bayi_id_6444c4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="destektalebi",
            index=models.Index(
                fields=["durum", "-son_mesaj_tarihi"],
                name="destek_dest_durum_12179d_idx",
            ),
        ),
    ]
