# Generated by Django 5.2.17 on 2026-09-03 18:55

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("basvurular", "0001_initial"),
        ("katalog", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Banka",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "olusturma_tarihi",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturma Tarihi"
                    ),
                ),
                (
                    "guncelleme_tarihi",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncelleme Tarihi"
                    ),
                ),
                (
                    "banka_adi",
                    models.CharField(max_length=100, verbose_name="Banka Adı"),
                ),
                (
                    "hesap_sahibi",
                    models.CharField(max_length=150, verbose_name="Hesap Sahibi"),
                ),
                (
                    "iban",
                    models.CharField(max_length=34, unique=True, verbose_name="IBAN"),
                ),
                (
                    "sube_kodu",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Şube Kodu"
                    ),
                ),
                (
                    "hesap_numarasi",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Hesap Numarası"
                    ),
                ),
                ("aciklama", models.TextField(blank=True, verbose_name="Açıklama")),
                (
                    "bakiye",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=14,
                        verbose_name="Banka Bakiyesi",
                    ),
                ),
                (
                    "bayiye_gorunur",
                    models.BooleanField(
                        default=True,
                        help_text="Kapalıysa bu hesap bayi panelinde listelenmez.",
                        verbose_name="Bayiye Görünür",
                    ),
                ),
                ("aktif", models.BooleanField(default=True, verbose_name="Aktif")),
            ],
            options={
                "verbose_name": "Banka Hesabı",
                "verbose_name_plural": "5. Banka Hesapları",
                "ordering": ["banka_adi"],
            },
        ),
        migrations.CreateModel(
            name="BayiGrubu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "olusturma_tarihi",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturma Tarihi"
                    ),
                ),
                (
                    "guncelleme_tarihi",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncelleme Tarihi"
                    ),
                ),
                (
                    "ad",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Grup Adı"
                    ),
                ),
                ("aciklama", models.TextField(blank=True, verbose_name="Açıklama")),
                (
                    "varsayilan_borc_limiti",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Bu gruptaki bayiler bakiyesi bittiğinde bu tutara kadar borçlanabilir.",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Varsayılan Borç Limiti",
                    ),
                ),
                ("aktif", models.BooleanField(default=True, verbose_name="Aktif")),
            ],
            options={
                "verbose_name": "Bayi Grubu",
                "verbose_name_plural": "1. Bayi Grupları",
                "ordering": ["ad"],
            },
        ),
        migrations.CreateModel(
            name="Cuzdan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "olusturma_tarihi",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturma Tarihi"
                    ),
                ),
                (
                    "guncelleme_tarihi",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncelleme Tarihi"
                    ),
                ),
                (
                    "bakiye",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Bakiye",
                    ),
                ),
                (
                    "borc",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Borç",
                    ),
                ),
                (
                    "borc_limiti",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Boş bırakılırsa bayi grubunun varsayılan limiti geçerli olur.",
                        max_digits=12,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Borç Limiti",
                    ),
                ),
                (
                    "islem_yapabilir",
                    models.BooleanField(
                        default=True,
                        help_text="Kapatılırsa bayi yeni başvuru gönderemez.",
                        verbose_name="İşlem Yapabilir",
                    ),
                ),
                (
                    "bayi",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cuzdan",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Bayi",
                    ),
                ),
                (
                    "grup",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cuzdanlar",
                        to="finans.bayigrubu",
                        verbose_name="Bayi Grubu",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cüzdan",
                "verbose_name_plural": "2. Cüzdanlar",
                "ordering": ["bayi__username"],
            },
        ),
        migrations.CreateModel(
            name="UcretKurali",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "olusturma_tarihi",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturma Tarihi"
                    ),
                ),
                (
                    "guncelleme_tarihi",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncelleme Tarihi"
                    ),
                ),
                ("ad", models.CharField(max_length=200, verbose_name="Kural Adı")),
                (
                    "yon",
                    models.CharField(
                        choices=[
                            ("tahsilat", "Tahsilat (bayiden alınır)"),
                            ("hakedis", "Hakediş (bayiye verilir)"),
                        ],
                        max_length=10,
                        verbose_name="Yön",
                    ),
                ),
                (
                    "tutar",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Bayiden alınacak ya da bayiye verilecek sabit tutar (₺).",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Tutar",
                    ),
                ),
                (
                    "baslangic_tarihi",
                    models.DateField(
                        blank=True, null=True, verbose_name="Başlangıç Tarihi"
                    ),
                ),
                (
                    "bitis_tarihi",
                    models.DateField(
                        blank=True, null=True, verbose_name="Bitiş Tarihi"
                    ),
                ),
                (
                    "oncelik",
                    models.IntegerField(
                        default=0,
                        help_text="Eşit özgüllükte birden fazla kural eşleşirse yüksek olan kazanır.",
                        verbose_name="Öncelik",
                    ),
                ),
                ("aktif", models.BooleanField(default=True, verbose_name="Aktif")),
                (
                    "bayi",
                    models.ForeignKey(
                        blank=True,
                        help_text="Yalnızca bu bayiye özel bir istisna tanımlamak için kullanın.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ozel_ucret_kurallari",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Tek Bayi",
                    ),
                ),
                (
                    "bayi_grubu",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ucret_kurallari",
                        to="finans.bayigrubu",
                        verbose_name="Bayi Grubu",
                    ),
                ),
                (
                    "kampanya",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ucret_kurallari",
                        to="katalog.kampanya",
                        verbose_name="Kampanya",
                    ),
                ),
                (
                    "kategori",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ucret_kurallari",
                        to="katalog.basvurukategorisi",
                        verbose_name="Kategori",
                    ),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ucret_kurallari",
                        to="katalog.operator",
                        verbose_name="Operatör",
                    ),
                ),
                (
                    "tarife",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ucret_kurallari",
                        to="katalog.tarife",
                        verbose_name="Tarife",
                    ),
                ),
                (
                    "tetikleyici_durum",
                    models.ForeignKey(
                        help_text="Başvuru bu duruma geçtiğinde kural işler. Genellikle 'Aktif'.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ucret_kurallari",
                        to="basvurular.basvurudurumu",
                        verbose_name="Tetikleyici Durum",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ücret Kuralı",
                "verbose_name_plural": "4. Ücret ve Hakediş Kuralları",
                "ordering": ["-oncelik", "ad"],
            },
        ),
        migrations.CreateModel(
            name="CuzdanHareketi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tip",
                    models.CharField(
                        choices=[
                            ("yukleme", "Bakiye Yükleme"),
                            ("tahsilat", "İşlem Ücreti Tahsilatı"),
                            ("hakedis", "Hakediş"),
                            ("borc_ekle", "Borç Ekleme"),
                            ("borc_tahsil", "Borç Tahsilatı"),
                            ("duzeltme", "Manuel Düzeltme"),
                            ("iptal", "İptal / Ters Kayıt"),
                        ],
                        max_length=20,
                        verbose_name="Hareket Tipi",
                    ),
                ),
                (
                    "tutar",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="İşlem Tutarı"
                    ),
                ),
                (
                    "onceki_bakiye",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Önceki Bakiye"
                    ),
                ),
                (
                    "sonraki_bakiye",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Sonraki Bakiye"
                    ),
                ),
                (
                    "onceki_borc",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Önceki Borç"
                    ),
                ),
                (
                    "sonraki_borc",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Sonraki Borç"
                    ),
                ),
                (
                    "idempotency_anahtari",
                    models.CharField(
                        help_text="Aynı olayın iki kez işlenmesini engeller.",
                        max_length=255,
                        unique=True,
                        verbose_name="Tekillik Anahtarı",
                    ),
                ),
                (
                    "aciklama",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Açıklama"
                    ),
                ),
                (
                    "tarih",
                    models.DateTimeField(auto_now_add=True, verbose_name="Tarih"),
                ),
                (
                    "banka",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hareketler",
                        to="finans.banka",
                        verbose_name="Banka",
                    ),
                ),
                (
                    "basvuru",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cuzdan_hareketleri",
                        to="basvurular.basvuru",
                        verbose_name="Kaynak Başvuru",
                    ),
                ),
                (
                    "cuzdan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hareketler",
                        to="finans.cuzdan",
                        verbose_name="Cüzdan",
                    ),
                ),
                (
                    "olusturan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="olusturdugu_hareketler",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="İşlemi Yapan",
                    ),
                ),
                (
                    "ters_kayit",
                    models.OneToOneField(
                        blank=True,
                        help_text="Bu hareket iptal edildiyse, iptal kaydını gösterir.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="iptal_edilen",
                        to="finans.cuzdanhareketi",
                        verbose_name="Ters Kaydı",
                    ),
                ),
                (
                    "kural",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hareketler",
                        to="finans.ucretkurali",
                        verbose_name="Uygulanan Kural",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cüzdan Hareketi",
                "verbose_name_plural": "3. Cüzdan Hareketleri",
                "ordering": ["-tarih", "-id"],
                "indexes": [
                    models.Index(
                        fields=["cuzdan", "-tarih"],
                        name="finans_cuzd_cuzdan__2a728a_idx",
                    ),
                    models.Index(
                        fields=["tip", "-tarih"], name="finans_cuzd_tip_2951ac_idx"
                    ),
                ],
            },
        ),
    ]
