# Generated by Django 5.2.17 on 2026-09-03 20:03

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finans", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="bayigrubu", name="varsayilan_borc_limiti",),
        migrations.AddField(
            model_name="cuzdan",
            name="borc_izni",
            field=models.BooleanField(
                default=False,
                help_text="Açılmadıkça bayi bakiyesinden fazlasını harcayamaz.",
                verbose_name="Borçlanabilir",
            ),
        ),
        migrations.AlterField(
            model_name="cuzdan",
            name="borc_limiti",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Yalnızca “Borçlanabilir” açıkken geçerlidir. Bayiye gösterilmez.",
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Borç Limiti",
            ),
        ),
    ]
