# Generated by Django 5.2.17 on 2026-09-03 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("finans", "0002_remove_bayigrubu_varsayilan_borc_limiti_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="cuzdan", name="borc_izni",),
        migrations.RemoveField(model_name="cuzdan", name="borc_limiti",),
    ]
