# Generated by Django 5.2.17 on 2026-09-03 23:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finans", "0003_remove_cuzdan_borc_izni_remove_cuzdan_borc_limiti"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="ucretkurali",
            name="tedarikci",
            field=models.ForeignKey(
                blank=True,
                help_text="Tedarikçi geliri kuralları için: fiyat tedarikçiden tedarikçiye değiştiğinde her biri için ayrı kural tanımlayın.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ozel_tedarikci_kurallari",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Tek Tedarikçi",
            ),
        ),
        migrations.AlterField(
            model_name="cuzdanhareketi",
            name="tip",
            field=models.CharField(
                choices=[
                    ("yukleme", "Bakiye Yükleme"),
                    ("tahsilat", "İşlem Ücreti Tahsilatı"),
                    ("hakedis", "Hakediş"),
                    ("tedarikci_bedeli", "Tedarikçi İşlem Bedeli"),
                    ("borc_ekle", "Borç Ekleme"),
                    ("borc_tahsil", "Borç Tahsilatı"),
                    ("duzeltme", "Manuel Düzeltme"),
                    ("iptal", "İptal / Ters Kayıt"),
                ],
                max_length=20,
                verbose_name="Hareket Tipi",
            ),
        ),
        migrations.AlterField(
            model_name="ucretkurali",
            name="yon",
            field=models.CharField(
                choices=[
                    ("tahsilat", "Tahsilat (bayiden alınır)"),
                    ("hakedis", "Hakediş (bayiye verilir)"),
                    ("tedarikci_geliri", "Tedarikçi Geliri (tedarikçiden alınır)"),
                ],
                max_length=20,
                verbose_name="Yön",
            ),
        ),
    ]
