# Generated by Django 5.2.17 on 2026-09-04 09:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finans", "0004_ucretkurali_tedarikci_alter_cuzdanhareketi_tip_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="cuzdanhareketi",
            name="tip",
            field=models.CharField(
                choices=[
                    ("yukleme", "Bakiye Yükleme"),
                    ("tahsilat", "İşlem Ücreti Tahsilatı"),
                    ("hakedis", "Hakediş"),
                    ("tedarikci_bedeli", "Tedarikçiden Tahsilat"),
                    ("borc_ekle", "Borç Ekleme"),
                    ("borc_tahsil", "Borç Tahsilatı"),
                    ("duzeltme", "Manuel Düzeltme"),
                    ("iptal", "İptal / Ters Kayıt"),
                ],
                max_length=20,
                verbose_name="Hareket Tipi",
            ),
        ),
        migrations.AlterField(
            model_name="ucretkurali",
            name="tedarikci",
            field=models.ForeignKey(
                blank=True,
                help_text="Ana hakediş kuralları için: tutar tedarikçiden tedarikçiye değiştiğinde her biri için ayrı kural tanımlayın. Operatörden alınan tutar için bu alanı boş bırakıp Operatör alanını doldurun.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ozel_tedarikci_kurallari",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Tek Tedarikçi",
            ),
        ),
        migrations.AlterField(
            model_name="ucretkurali",
            name="yon",
            field=models.CharField(
                choices=[
                    ("tahsilat", "Tahsilat (bayiden alınır)"),
                    ("hakedis", "Hakediş (bayiye verilir)"),
                    (
                        "tedarikci_geliri",
                        "Ana Hakediş (operatörden ya da tedarikçiden alınır)",
                    ),
                ],
                max_length=20,
                verbose_name="Yön",
            ),
        ),
    ]
