# Generated by Django 5.2.17 on 2026-09-04 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "finans",
            "0005_alter_cuzdanhareketi_tip_alter_ucretkurali_tedarikci_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="ucretkurali",
            name="ad",
            field=models.CharField(
                blank=True,
                help_text="Boş bırakılırsa kapsamdan üretilir (ör. “Red 20 GB · bayiye hakediş”).",
                max_length=200,
                verbose_name="Kural Adı",
            ),
        ),
    ]
