# Generated by Django 5.2.17 on 2026-09-04 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finans", "0006_alter_ucretkurali_ad"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ucretkurali",
            name="yon",
            field=models.CharField(
                choices=[
                    ("tedarikci_geliri", "Alışım (operatörden ya da tedarikçiden)"),
                    ("hakedis", "Bayiye ödenecek (bayi fiyat listesi)"),
                    ("tahsilat", "Bayiden tahsil edilecek"),
                ],
                max_length=20,
                verbose_name="Yön",
            ),
        ),
    ]
