# Generated by Django 5.2.17 on 2026-09-04 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("finans", "0007_alter_ucretkurali_yon"),
    ]

    operations = [
        migrations.RemoveField(model_name="ucretkurali", name="kampanya",),
    ]
