# Generated by Django 5.2.17 on 2026-09-05 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finans", "0008_remove_ucretkurali_kampanya"),
        ("katalog", "0008_kampanya"),
    ]

    operations = [
        migrations.AddField(
            model_name="ucretkurali",
            name="kampanya",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ucret_kurallari",
                to="katalog.kampanya",
                verbose_name="Kampanya",
            ),
        ),
    ]
