# Generated by Django 5.2.17 on 2026-09-05 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finans", "0009_ucretkurali_kampanya"),
    ]

    operations = [
        migrations.AddField(
            model_name="cuzdanhareketi",
            name="giris_bedeli",
            field=models.BooleanField(
                default=False,
                help_text="Başvuru girilirken alınan bedel. Yalnızca başvuru olumsuz sonuçlanınca iade edilir; ara durumlarda geri alınmaz.",
                verbose_name="Giriş Bedeli Hareketi",
            ),
        ),
    ]
