# Generated by Django 5.2.17 on 2026-09-05 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finans", "0010_cuzdanhareketi_giris_bedeli"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cuzdanhareketi",
            name="tip",
            field=models.CharField(
                choices=[
                    ("yukleme", "Bakiye Yükleme"),
                    ("tahsilat", "İşlem Ücreti Tahsilatı"),
                    ("hakedis", "Hakediş"),
                    ("tedarikci_bedeli", "Tedarikçiden Tahsilat"),
                    ("borc_ekle", "Borç Ekleme"),
                    ("borc_tahsil", "Borç Tahsilatı"),
                    ("iade", "Bayiye İade / Ödeme"),
                    ("duzeltme", "Manuel Düzeltme"),
                    ("iptal", "İptal / Ters Kayıt"),
                ],
                max_length=20,
                verbose_name="Hareket Tipi",
            ),
        ),
    ]
