# Generated by Django 5.2.17 on 2026-09-05 11:19

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finans", "0011_alter_cuzdanhareketi_tip"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OdemeBildirimi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "olusturma_tarihi",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturma Tarihi"
                    ),
                ),
                (
                    "guncelleme_tarihi",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncelleme Tarihi"
                    ),
                ),
                (
                    "tutar",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Tutar",
                    ),
                ),
                (
                    "gonderen_adi",
                    models.CharField(
                        help_text="Havaleyi yapan kişi ya da firma; hesap ekstresinde bu adla görünür.",
                        max_length=150,
                        verbose_name="Gönderen Adı",
                    ),
                ),
                (
                    "aciklama",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Açıklama"
                    ),
                ),
                (
                    "durum",
                    models.CharField(
                        choices=[
                            ("bekliyor", "Bekliyor"),
                            ("onaylandi", "Onaylandı"),
                            ("reddedildi", "Reddedildi"),
                        ],
                        default="bekliyor",
                        max_length=20,
                        verbose_name="Durum",
                    ),
                ),
                (
                    "karar_tarihi",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        null=True,
                        verbose_name="Karar Tarihi",
                    ),
                ),
                (
                    "karar_notu",
                    models.CharField(
                        blank=True,
                        help_text="Reddedildiyse sebebi. Bayiye gösterilir.",
                        max_length=255,
                        verbose_name="Karar Notu",
                    ),
                ),
                (
                    "banka",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="odeme_bildirimleri",
                        to="finans.banka",
                        verbose_name="Yatırılan Hesap",
                    ),
                ),
                (
                    "bayi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="odeme_bildirimleri",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Bayi",
                    ),
                ),
                (
                    "karar_veren",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="karar_verdigi_odeme_bildirimleri",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Kararı Veren",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ödeme Bildirimi",
                "verbose_name_plural": "Ödeme Bildirimleri",
                "ordering": ["-olusturma_tarihi"],
                "indexes": [
                    models.Index(
                        fields=["durum", "-olusturma_tarihi"],
                        name="finans_odem_durum_d0bac1_idx",
                    )
                ],
            },
        ),
    ]
