# Generated by Django 5.2.17 on 2026-09-05 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("finans", "0012_odeme_bildirimi"),
    ]

    operations = [
        migrations.CreateModel(
            name="OperatorAlisi",
            fields=[],
            options={
                "verbose_name": "Operatörden Alış",
                "verbose_name_plural": "Operatörden Alışlarım",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("finans.ucretkurali",),
        ),
        migrations.CreateModel(
            name="TedarikciAlisi",
            fields=[],
            options={
                "verbose_name": "Tedarikçiden Alış",
                "verbose_name_plural": "Tedarikçiden Alışlarım",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("finans.ucretkurali",),
        ),
    ]
