# Generated by Django 5.2.17 on 2026-09-05 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finans", "0013_alis_ekranlari"),
    ]

    operations = [
        migrations.AddField(
            model_name="odemebildirimi",
            name="para_surumu",
            field=models.PositiveIntegerField(
                default=0,
                editable=False,
                help_text="Onay her geri alındığında artar. Defterdeki tekillik anahtarı bu sayıyı içerir; geri alınıp yeniden onaylanan bildirimin ikinci hareketi aynı anahtara çarpıp sessizce yutulmasın.",
                verbose_name="Para İşlem Sürümü",
            ),
        ),
    ]
