# Generated by Django 5.2.17 on 2026-09-05 20:13

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finans", "0015_alter_cuzdanhareketi_tip"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ucretkurali",
            name="tutar",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Sabit tutar (₺). Yöne göre: bayiden alınacak, bayiye verilecek ya da hattı alırken ödenecek.",
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Tutar",
            ),
        ),
    ]
