# Generated by Django 5.2.17 on 2026-09-05 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finans", "0016_alter_ucretkurali_tutar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cuzdanhareketi",
            name="tip",
            field=models.CharField(
                choices=[
                    ("yukleme", "Bakiye Yükleme"),
                    ("tahsilat", "İşlem Ücreti Tahsilatı"),
                    ("hakedis", "Hakediş"),
                    ("tedarikci_bedeli", "Tedarikçiye Ödeme"),
                    ("tedarikci_primi", "Tedarikçiden Alınan Prim"),
                    ("borc_ekle", "Borç Ekleme"),
                    ("borc_tahsil", "Borç Tahsilatı"),
                    ("iade", "Bayiye İade / Ödeme"),
                    ("duzeltme", "Manuel Düzeltme"),
                    ("iptal", "İptal / Ters Kayıt"),
                ],
                max_length=20,
                verbose_name="Hareket Tipi",
            ),
        ),
        migrations.AlterField(
            model_name="ucretkurali",
            name="yon",
            field=models.CharField(
                choices=[
                    (
                        "tedarikci_geliri",
                        "Maliyetim (operatöre ya da tedarikçiye ödediğim)",
                    ),
                    ("ana_prim", "Aldığım prim (operatörden ya da tedarikçiden)"),
                    ("hakedis", "Bayiye ödenecek (bayi fiyat listesi)"),
                    ("tahsilat", "Bayiden tahsil edilecek"),
                ],
                max_length=20,
                verbose_name="Yön",
            ),
        ),
    ]
