# Generated by Django 5.2.17 on 2026-09-05 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("finans", "0017_alter_cuzdanhareketi_tip_alter_ucretkurali_yon"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="operatoralisi",
            options={
                "verbose_name": "Operatör Hesabı",
                "verbose_name_plural": "Operatörle Hesabım",
            },
        ),
        migrations.AlterModelOptions(
            name="tedarikcialisi",
            options={
                "verbose_name": "Tedarikçi Hesabı",
                "verbose_name_plural": "Tedarikçiyle Hesabım",
            },
        ),
    ]
