# Generated by Django 5.2.17 on 2026-09-08 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finans", "0018_alter_operatoralisi_options_and_more"),
        ("magaza", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cuzdanhareketi",
            name="siparis",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cuzdan_hareketleri",
                to="magaza.siparis",
                verbose_name="Kaynak Sipariş",
            ),
        ),
        migrations.AlterField(
            model_name="cuzdanhareketi",
            name="tip",
            field=models.CharField(
                choices=[
                    ("yukleme", "Bakiye Yükleme"),
                    ("tahsilat", "İşlem Ücreti Tahsilatı"),
                    ("hakedis", "Hakediş"),
                    ("tedarikci_bedeli", "Tedarikçiye Ödeme"),
                    ("tedarikci_primi", "Tedarikçiden Alınan Prim"),
                    ("borc_ekle", "Borç Ekleme"),
                    ("borc_tahsil", "Borç Tahsilatı"),
                    ("iade", "Bayiye İade / Ödeme"),
                    ("siparis", "Ürün Siparişi"),
                    ("duzeltme", "Manuel Düzeltme"),
                    ("iptal", "İptal / Ters Kayıt"),
                ],
                max_length=20,
                verbose_name="Hareket Tipi",
            ),
        ),
    ]
