# Generated by Django 5.2.17 on 2026-09-11 21:36

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finans", "0019_cuzdanhareketi_siparis_alter_cuzdanhareketi_tip"),
    ]

    operations = [
        migrations.AddField(
            model_name="bayigrubu",
            name="esim_kar_orani",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Bu gruptaki bayilere eSIM paketleri alışın üzerine bu yüzdeyle satılır (44 → alış × 1,44). Boş bırakılırsa her paketin kendi kâr oranı geçerlidir.",
                max_digits=6,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                verbose_name="eSIM Kâr Oranı (%)",
            ),
        ),
    ]
