# Generated by Django 5.2.17 on 2026-09-11 22:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finans", "0020_bayigrubu_esim_kar_orani"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bayigrubu",
            name="esim_kar_orani",
            field=models.IntegerField(
                blank=True,
                help_text="Bu gruptaki bayiye eSIM fiyatı, normal bayi fiyatının üzerine bu yüzde eklenerek gösterilir (34 ₺ ve +10 → 37 ₺). Eksi girilirse indirim. Boşsa fark yok. Kaydedince bayi ekranında anında geçerli olur.",
                null=True,
                validators=[django.core.validators.MinValueValidator(-99)],
                verbose_name="eSIM Fiyat Farkı (%)",
            ),
        ),
    ]
