# Generated by Django 5.2.17 on 2026-09-13 17:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finans", "0021_alter_bayigrubu_esim_kar_orani"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bayigrubu",
            name="esim_kar_orani",
            field=models.IntegerField(
                blank=True,
                help_text="Bu gruptaki bayi her eSIM'i normal bayi fiyatından bu yüzde kadar PAHALI alır ve cüzdanından o tutar düşer (230 ₺ ve +25 → bayi 287 ₺ öder). Eksi girilirse indirim, boşsa fark yok. Bayinin müşteriye kârı bu DEĞİLDİR — o oran Ayarlar → Genel Ayarlar'daki “eSIM Tavsiye Edilen Satış Kâr Oranı”dır. Çoğu grupta boş kalır.",
                null=True,
                validators=[django.core.validators.MinValueValidator(-99)],
                verbose_name="eSIM'i Bu Kadar Pahalı Öder (%)",
            ),
        ),
    ]
