# Generated by Django 5.2.17 on 2026-09-13 17:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finans", "0022_esim_kar_orani_etiketi"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bayigrubu",
            name="esim_kar_orani",
            field=models.IntegerField(
                blank=True,
                help_text="Bu gruptaki bayinin müşteriye kârı. Bayi paketi bizim fiyattan öder; ekranda “müşteriye şu fiyata sat” diye bu yüzde eklenmiş rakamı görür, küsurat atılır (230 ₺ ve 25 → 287 ₺; 57 ₺ bayinin). Boş ya da 0 ise tavsiye fiyat gösterilmez, bayi yalnızca kendi fiyatını görür. Kaydedince bayi ekranında anında geçerli olur.",
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="eSIM Satış Kârı (%)",
            ),
        ),
    ]
