# Generated by Django 5.2.17 on 2026-09-29 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finans", "0023_alter_bayigrubu_esim_kar_orani"),
        ("kontor", "0006_fiyat_grubu"),
    ]

    operations = [
        migrations.AddField(
            model_name="cuzdan",
            name="kontor_grubu",
            field=models.ForeignKey(
                blank=True,
                help_text="Boşsa varsayılan kontör grubu geçerlidir.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cuzdanlar",
                to="kontor.fiyatgrubu",
                verbose_name="Kontör Fiyat Grubu",
            ),
        ),
    ]
