# Generated by Django 5.2.17 on 2026-10-10 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finans", "0024_cuzdan_kontor_grubu"),
        ("kontor", "0022_kategori_tam_kontor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cuzdan",
            name="kontor_grubu",
            field=models.ForeignKey(
                blank=True,
                help_text="Kontör ve fatura fiyatları bu gruptan. Boşsa varsayılan grup geçerlidir.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cuzdanlar",
                to="kontor.fiyatgrubu",
                verbose_name="Fiyat Grubu (kontör, fatura)",
            ),
        ),
    ]
