# Generated by Django 5.2.17 on 2026-09-27 22:12

import apps.kontor.saglayicilar
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("finans", "0023_alter_bayigrubu_esim_kar_orani"),
        ("katalog", "0016_kategorialani_tarifeler"),
        ("magaza", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Saglayici",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "olusturma_tarihi",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturma Tarihi"
                    ),
                ),
                (
                    "guncelleme_tarihi",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncelleme Tarihi"
                    ),
                ),
                (
                    "ad",
                    models.CharField(max_length=100, unique=True, verbose_name="Ad"),
                ),
                (
                    "tur",
                    models.CharField(
                        choices=apps.kontor.saglayicilar.saglayici_secenekleri,
                        help_text="Hangi protokolle konuşulacağı. Yeni bir yazılım türü kodla eklenir.",
                        max_length=30,
                        verbose_name="Yazılımı",
                    ),
                ),
                (
                    "adres",
                    models.CharField(
                        help_text="Alan adı (ornek-kontor.com) ya da http(s):// ile tam adres.",
                        max_length=200,
                        verbose_name="Site Adresi",
                    ),
                ),
                (
                    "bayi_kodu",
                    models.CharField(
                        blank=True,
                        help_text="Teknografi ister; Znet/Gencan yalnızca fiyat listesi çekerken kullanır, kntryeni hiç kullanmaz.",
                        max_length=100,
                        verbose_name="Bayi Kodu",
                    ),
                ),
                (
                    "kullanici_adi",
                    models.CharField(max_length=100, verbose_name="Kullanıcı Adı"),
                ),
                ("sifre", models.CharField(max_length=200, verbose_name="Şifre")),
                (
                    "ref_sayaci",
                    models.PositiveBigIntegerField(
                        default=1000,
                        help_text="Sağlayıcıya giden tekil numara buradan artarak verilir. Sağlayıcı aynı numarayı ikinci kez kabul etmez: eski sistemde bu hesapla işlem yapıldıysa oradaki sayının üstünde bir değerle başlatın.",
                        verbose_name="Sıradaki Referans No",
                    ),
                ),
                (
                    "aktif",
                    models.BooleanField(
                        default=True,
                        help_text="Kapatılırsa hiçbir işlem bu sağlayıcıya gönderilmez; sıradaki denenir.",
                        verbose_name="Aktif",
                    ),
                ),
                (
                    "son_liste_cekme",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        null=True,
                        verbose_name="Fiyat Listesi Çekildi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kontör Sağlayıcısı",
                "verbose_name_plural": "Kontör Sağlayıcıları",
                "ordering": ["ad"],
            },
        ),
        migrations.CreateModel(
            name="ApiErisimi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "olusturma_tarihi",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturma Tarihi"
                    ),
                ),
                (
                    "guncelleme_tarihi",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncelleme Tarihi"
                    ),
                ),
                (
                    "bayi_kodu",
                    models.CharField(
                        blank=True,
                        help_text="Programa yazılacak kullanıcı kodu. Boş bırakılırsa bayinin telefon numarası olur.",
                        max_length=64,
                        unique=True,
                        verbose_name="Bayi Kodu",
                    ),
                ),
                (
                    "anahtar_ozeti",
                    models.CharField(blank=True, editable=False, max_length=64),
                ),
                ("aktif", models.BooleanField(default=True, verbose_name="Aktif")),
                (
                    "son_kullanim",
                    models.DateTimeField(
                        blank=True, editable=False, null=True, verbose_name="Son İstek"
                    ),
                ),
                (
                    "kullanici",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kontor_api",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Bayi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bayi API Erişimi",
                "verbose_name_plural": "Bayi API Erişimleri",
                "ordering": ["bayi_kodu"],
            },
        ),
        migrations.CreateModel(
            name="Kategori",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "olusturma_tarihi",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturma Tarihi"
                    ),
                ),
                (
                    "guncelleme_tarihi",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncelleme Tarihi"
                    ),
                ),
                (
                    "ad",
                    models.CharField(max_length=120, unique=True, verbose_name="Ad"),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=140, unique=True, verbose_name="Kısa Ad"
                    ),
                ),
                (
                    "hedef",
                    models.CharField(
                        choices=[
                            ("telefon", "Telefon numarası"),
                            ("hesap", "Oyuncu / hesap numarası"),
                            ("yok", "Hedef yok (pin kodu döner)"),
                        ],
                        default="telefon",
                        help_text="Telefon: 10 haneli cep numarası istenir. Hesap: oyuncu ID gibi serbest metin. Hedef yok: pin satışı; kod sağlayıcının cevabıyla bayiye gösterilir.",
                        max_length=10,
                        verbose_name="Yükleme Nereye",
                    ),
                ),
                (
                    "hedef_etiketi",
                    models.CharField(
                        blank=True,
                        help_text="Formda kutunun üstünde yazan. Boşsa “Telefon numarası” / “Oyuncu ID”.",
                        max_length=60,
                        verbose_name="Hedef Etiketi",
                    ),
                ),
                (
                    "api_operator",
                    models.CharField(
                        blank=True,
                        help_text="Protokoldeki operatör adı (vodafone, turkcell, avea…). Bayilerin programlarından gelen istek kategoriyi bununla bulur; sağlayıcıya da rotada ayrı yazılmadıysa bu gider.",
                        max_length=40,
                        verbose_name="Operatör Kodu",
                    ),
                ),
                (
                    "api_tip",
                    models.CharField(
                        blank=True,
                        help_text="Protokoldeki tip (ses, tam, tl…). Operatör koduyla birlikte kategoriyi belirler.",
                        max_length=40,
                        verbose_name="Tip Kodu",
                    ),
                ),
                (
                    "aciklama",
                    models.TextField(
                        blank=True,
                        help_text="Bayi paket listesinin üstünde görür.",
                        verbose_name="Açıklama",
                    ),
                ),
                ("sira", models.PositiveIntegerField(default=0, verbose_name="Sıra")),
                ("aktif", models.BooleanField(default=True, verbose_name="Aktif")),
                (
                    "operator",
                    models.ForeignKey(
                        blank=True,
                        help_text="Oyun ve pin kategorilerinde boş bırakılır.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="kontor_kategorileri",
                        to="katalog.operator",
                        verbose_name="Operatör",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kontör Kategorisi",
                "verbose_name_plural": "Kontör Kategorileri",
                "ordering": ["sira", "ad"],
            },
        ),
        migrations.CreateModel(
            name="Paket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "olusturma_tarihi",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturma Tarihi"
                    ),
                ),
                (
                    "guncelleme_tarihi",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncelleme Tarihi"
                    ),
                ),
                (
                    "kod",
                    models.CharField(
                        help_text="Bayi programları paketi bu kodla ister (kontor=100). Sağlayıcıya rotada ayrı kod yazılmadıysa bu gider.",
                        max_length=40,
                        verbose_name="Kupür / Ürün Kodu",
                    ),
                ),
                ("ad", models.CharField(max_length=150, verbose_name="Ad")),
                (
                    "aciklama",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Açıklama"
                    ),
                ),
                (
                    "dakika",
                    models.PositiveIntegerField(default=0, verbose_name="Dakika"),
                ),
                (
                    "internet_mb",
                    models.PositiveIntegerField(
                        default=0, verbose_name="İnternet (MB)"
                    ),
                ),
                ("sms", models.PositiveIntegerField(default=0, verbose_name="SMS")),
                ("gun", models.PositiveIntegerField(default=0, verbose_name="Gün")),
                (
                    "satis_fiyati",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Bayinin bakiyesinden düşülecek tutar. Bayi grubuna özel fiyat alttaki tablodan girilir; girilmeyen grup bunu öder. 0 ise paket satılmaz.",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Bayiye Satış",
                    ),
                ),
                ("sira", models.PositiveIntegerField(default=0, verbose_name="Sıra")),
                ("aktif", models.BooleanField(default=True, verbose_name="Aktif")),
                (
                    "kategori",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="paketler",
                        to="kontor.kategori",
                        verbose_name="Kategori",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kontör Paketi",
                "verbose_name_plural": "Kontör Paketleri",
                "ordering": [
                    "kategori__sira",
                    "kategori__ad",
                    "sira",
                    "satis_fiyati",
                    "ad",
                ],
            },
        ),
        migrations.CreateModel(
            name="PaketFiyati",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fiyat",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Satış",
                    ),
                ),
                (
                    "grup",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kontor_fiyatlari",
                        to="finans.bayigrubu",
                        verbose_name="Bayi Grubu",
                    ),
                ),
                (
                    "paket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grup_fiyatlari",
                        to="kontor.paket",
                        verbose_name="Paket",
                    ),
                ),
            ],
            options={
                "verbose_name": "Grup Fiyatı",
                "verbose_name_plural": "Bayi Grubuna Göre Fiyat",
            },
        ),
        migrations.CreateModel(
            name="Rota",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sira",
                    models.PositiveSmallIntegerField(default=1, verbose_name="Sıra"),
                ),
                (
                    "uzak_kod",
                    models.CharField(
                        blank=True, max_length=60, verbose_name="Sağlayıcıdaki Kodu"
                    ),
                ),
                (
                    "uzak_operator",
                    models.CharField(
                        blank=True, max_length=60, verbose_name="Operatör"
                    ),
                ),
                (
                    "uzak_tip",
                    models.CharField(blank=True, max_length=60, verbose_name="Tip"),
                ),
                (
                    "alis_fiyati",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Bu sağlayıcıdan maliyet. Sağlayıcı cevapta tutar vermezse kâr bununla hesaplanır; fiyat listesi çekilebilen sağlayıcıda kendiliğinden güncellenir.",
                        max_digits=12,
                        null=True,
                        verbose_name="Alış",
                    ),
                ),
                ("aktif", models.BooleanField(default=True, verbose_name="Aktif")),
                (
                    "paket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rotalar",
                        to="kontor.paket",
                        verbose_name="Paket",
                    ),
                ),
                (
                    "saglayici",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rotalar",
                        to="kontor.saglayici",
                        verbose_name="Sağlayıcı",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sağlayıcı Sırası",
                "verbose_name_plural": "Sağlayıcı Sırası",
                "ordering": ["sira", "pk"],
            },
        ),
        migrations.CreateModel(
            name="Islem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "olusturma_tarihi",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturma Tarihi"
                    ),
                ),
                (
                    "guncelleme_tarihi",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncelleme Tarihi"
                    ),
                ),
                ("paket_adi", models.CharField(max_length=200, verbose_name="Paket")),
                (
                    "hedef",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=64,
                        verbose_name="Numara / Hesap",
                    ),
                ),
                (
                    "kanal",
                    models.CharField(
                        choices=[("panel", "Panel"), ("api", "Bayi programı")],
                        default="panel",
                        max_length=10,
                        verbose_name="Kanal",
                    ),
                ),
                (
                    "bayi_ref",
                    models.CharField(
                        blank=True,
                        help_text="Bayi programının gönderdiği tekil numara; sonucu bununla sorar.",
                        max_length=64,
                        verbose_name="Bayinin Referansı",
                    ),
                ),
                (
                    "durum",
                    models.CharField(
                        choices=[
                            ("sirada", "Sırada"),
                            ("islemde", "İşlemde"),
                            ("basarili", "Yüklendi"),
                            ("askida", "Askıda"),
                            ("iptal", "İptal edildi"),
                        ],
                        db_index=True,
                        default="sirada",
                        max_length=10,
                        verbose_name="Durum",
                    ),
                ),
                (
                    "sonuc_mesaji",
                    models.TextField(
                        blank=True,
                        help_text="Bayiye gösterilir: sağlayıcının mesajı, pin kodu ya da iptal sebebi.",
                        verbose_name="Sonuç",
                    ),
                ),
                (
                    "alis_tutari",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Alış",
                    ),
                ),
                (
                    "sonuc_tarihi",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Sonuç Tarihi"
                    ),
                ),
                (
                    "son_sorgu",
                    models.DateTimeField(
                        blank=True, editable=False, null=True, verbose_name="Son Sorgu"
                    ),
                ),
                (
                    "kilit_bitis",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "bayi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="kontor_islemleri",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Bayi",
                    ),
                ),
                (
                    "siparis",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="kontor",
                        to="magaza.siparis",
                        verbose_name="Sipariş",
                    ),
                ),
                (
                    "kategori",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="islemler",
                        to="kontor.kategori",
                        verbose_name="Kategori",
                    ),
                ),
                (
                    "paket",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="islemler",
                        to="kontor.paket",
                        verbose_name="Paket",
                    ),
                ),
                (
                    "saglayici",
                    models.ForeignKey(
                        blank=True,
                        help_text="İşlemin şu an bulunduğu ya da yüklendiği sağlayıcı.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="islemler",
                        to="kontor.saglayici",
                        verbose_name="Sağlayıcı",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kontör İşlemi",
                "verbose_name_plural": "Kontör İşlemleri",
                "ordering": ["-olusturma_tarihi"],
            },
        ),
        migrations.CreateModel(
            name="Deneme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ref", models.CharField(max_length=40, verbose_name="Bizim Referans")),
                (
                    "uzak_ref",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="Sağlayıcının İşlem No"
                    ),
                ),
                (
                    "uzak_kod",
                    models.CharField(
                        blank=True, max_length=60, verbose_name="Giden Kod"
                    ),
                ),
                (
                    "uzak_operator",
                    models.CharField(
                        blank=True, max_length=60, verbose_name="Giden Operatör"
                    ),
                ),
                (
                    "uzak_tip",
                    models.CharField(
                        blank=True, max_length=60, verbose_name="Giden Tip"
                    ),
                ),
                (
                    "durum",
                    models.CharField(
                        choices=[
                            ("gonderiliyor", "Gönderiliyor"),
                            ("islemde", "İşlemde"),
                            ("basarili", "Başarılı"),
                            ("reddedildi", "Reddedildi"),
                            ("belirsiz", "Cevap belirsiz"),
                        ],
                        default="gonderiliyor",
                        max_length=15,
                        verbose_name="Durum",
                    ),
                ),
                (
                    "elle",
                    models.BooleanField(
                        default=False,
                        help_text="Yönetici askıdaki işlemi bilerek bu sağlayıcıya gönderdi.",
                        verbose_name="Elle Gönderildi",
                    ),
                ),
                (
                    "gonderim_cevabi",
                    models.TextField(blank=True, verbose_name="Gönderim Cevabı"),
                ),
                (
                    "sonuc_cevabi",
                    models.TextField(blank=True, verbose_name="Son Sorgu Cevabı"),
                ),
                (
                    "alis",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Alış",
                    ),
                ),
                (
                    "olusturma_tarihi",
                    models.DateTimeField(auto_now_add=True, verbose_name="Gönderildi"),
                ),
                (
                    "guncelleme_tarihi",
                    models.DateTimeField(auto_now=True, verbose_name="Güncellendi"),
                ),
                (
                    "islem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="denemeler",
                        to="kontor.islem",
                        verbose_name="İşlem",
                    ),
                ),
                (
                    "saglayici",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="denemeler",
                        to="kontor.saglayici",
                        verbose_name="Sağlayıcı",
                    ),
                ),
            ],
            options={
                "verbose_name": "Gönderim",
                "verbose_name_plural": "Gönderimler",
                "ordering": ["olusturma_tarihi", "pk"],
            },
        ),
        migrations.CreateModel(
            name="SaglayiciPaketi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kod", models.CharField(max_length=60, verbose_name="Ürün Kodu")),
                ("ad", models.CharField(max_length=200, verbose_name="Ad")),
                (
                    "fiyat",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Alış"
                    ),
                ),
                (
                    "operator",
                    models.CharField(
                        blank=True, max_length=60, verbose_name="Operatör"
                    ),
                ),
                (
                    "tip",
                    models.CharField(blank=True, max_length=60, verbose_name="Tip"),
                ),
                (
                    "cekilme",
                    models.DateTimeField(auto_now=True, verbose_name="Çekildi"),
                ),
                (
                    "saglayici",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="liste",
                        to="kontor.saglayici",
                        verbose_name="Sağlayıcı",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sağlayıcı Fiyatı",
                "verbose_name_plural": "Sağlayıcı Fiyat Listeleri",
                "ordering": ["saglayici", "operator", "ad"],
            },
        ),
        migrations.AddConstraint(
            model_name="kategori",
            constraint=models.UniqueConstraint(
                condition=models.Q(("api_operator", ""), _negated=True),
                fields=("api_operator", "api_tip"),
                name="kontor_kategori_api_kodu",
            ),
        ),
        migrations.AddConstraint(
            model_name="paket",
            constraint=models.UniqueConstraint(
                fields=("kategori", "kod"), name="kontor_paket_kod"
            ),
        ),
        migrations.AddConstraint(
            model_name="paketfiyati",
            constraint=models.UniqueConstraint(
                fields=("paket", "grup"), name="kontor_paket_grup_fiyat"
            ),
        ),
        migrations.AddConstraint(
            model_name="rota",
            constraint=models.UniqueConstraint(
                fields=("paket", "saglayici"), name="kontor_rota_tekil"
            ),
        ),
        migrations.AddIndex(
            model_name="islem",
            index=models.Index(
                fields=["durum", "olusturma_tarihi"],
                name="kontor_isle_durum_9b29a2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="islem",
            index=models.Index(
                fields=["bayi", "-olusturma_tarihi"],
                name="kontor_isle_bayi_id_a898db_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="islem",
            constraint=models.UniqueConstraint(
                condition=models.Q(("bayi_ref", ""), _negated=True),
                fields=("bayi", "bayi_ref"),
                name="kontor_islem_bayi_ref",
            ),
        ),
        migrations.AddConstraint(
            model_name="deneme",
            constraint=models.UniqueConstraint(
                fields=("saglayici", "ref"), name="kontor_deneme_ref"
            ),
        ),
        migrations.AddConstraint(
            model_name="saglayicipaketi",
            constraint=models.UniqueConstraint(
                fields=("saglayici", "kod"), name="kontor_saglayici_paket_kod"
            ),
        ),
    ]
