# Generated by Django 5.2.17 on 2026-09-27 23:39

import apps.kontor.sorgu
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kontor", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="kategori",
            name="sorgu_kaynagi",
            field=models.CharField(
                blank=True,
                choices=apps.kontor.sorgu.kaynak_secenekleri,
                help_text="Seçilirse bayi numarayı yazıp bu numaranın alabileceği paketleri görür. Kaynaklar apps/kontor/sorgu/ klasöründeki dosyalardır. Sorgu satışı durdurmaz: cevap gelmezse paketler yine seçilebilir.",
                max_length=40,
                verbose_name="Numara Sorgusu",
            ),
        ),
    ]
