# Generated by Django 5.2.17 on 2026-09-27 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kontor", "0002_sorgu_kaynagi"),
    ]

    operations = [
        migrations.AddField(
            model_name="kategori",
            name="sorgu_sahibi_goster",
            field=models.BooleanField(
                default=True,
                help_text="Sorgu sonucunun üstünde hat sahibinin maskeli adı (Ah*** Yı***) yazar; bayi yanlış numarayı yüklemeden önce müşteriye teyit eder. Ad hiçbir yere kaydedilmez. Kapatılırsa kaynağa hiç sorulmaz.",
                verbose_name="Hat Sahibini Göster",
            ),
        ),
        migrations.CreateModel(
            name="GorulenPaket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kaynak",
                    models.CharField(max_length=40, verbose_name="Sorgu Kaynağı"),
                ),
                ("kod", models.CharField(max_length=60, verbose_name="Paket ID")),
                ("ad", models.CharField(blank=True, max_length=200, verbose_name="Ad")),
                ("aciklama", models.TextField(blank=True, verbose_name="Açıklama")),
                (
                    "fiyat",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Operatör Fiyatı",
                    ),
                ),
                (
                    "onceki_fiyat",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Fiyat değiştiyse bir önceki değer.",
                        max_digits=12,
                        null=True,
                        verbose_name="Önceki Fiyat",
                    ),
                ),
                (
                    "fiyat_degisme",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fiyat Değişti"
                    ),
                ),
                (
                    "ilk_gorulme",
                    models.DateTimeField(auto_now_add=True, verbose_name="İlk Görülme"),
                ),
                ("son_gorulme", models.DateTimeField(verbose_name="Son Görülme")),
                (
                    "gorulme_sayisi",
                    models.PositiveIntegerField(default=1, verbose_name="Görülme"),
                ),
                (
                    "yok_say",
                    models.BooleanField(
                        default=False,
                        help_text="Kataloğa eklenmeyecek; yeni paket rozetinde sayılmaz.",
                        verbose_name="Yok Say",
                    ),
                ),
                (
                    "kategori",
                    models.ForeignKey(
                        blank=True,
                        help_text="En son hangi kategorinin sorgusunda görüldüğü; Kataloğa ekle buraya açar.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="gorulen_paketler",
                        to="kontor.kategori",
                        verbose_name="Kategori",
                    ),
                ),
            ],
            options={
                "verbose_name": "Görülen Paket",
                "verbose_name_plural": "Operatörde Görülen Paketler",
                "ordering": ["-ilk_gorulme"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("kaynak", "kod"), name="kontor_gorulen_paket_kod"
                    )
                ],
            },
        ),
    ]
