# Generated by Django 5.2.17 on 2026-09-28 00:14

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kontor", "0003_gorulen_paket"),
    ]

    operations = [
        migrations.AddField(
            model_name="islem",
            name="tavsiye_fiyati",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="İşlem anında bayiye gösterilen müşteri fiyatı; paketin fiyatı sonra değişse de kalır.",
                max_digits=12,
                null=True,
                verbose_name="Tavsiye Satış",
            ),
        ),
        migrations.AddField(
            model_name="paket",
            name="tavsiye_fiyati",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Bayinin müşteriye söyleyeceği fiyat — çoğu zaman operatörün liste fiyatı. Doluysa bayi ekranında büyük rakam budur; bayinin alışı ve kazancı göz düğmesiyle açılır. Operatör sorgusunda görülen fiyattan doldurulabilir.",
                max_digits=12,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Tavsiye Satış",
            ),
        ),
    ]
