# Generated by Django 5.2.17 on 2026-09-28 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kontor", "0004_tavsiye_fiyati"),
    ]

    operations = [
        migrations.AddField(
            model_name="kategori",
            name="gorsel",
            field=models.ImageField(
                blank=True,
                help_text="Oyun kartında gösterilir (kare, sade logo). Küçültülüp WebP'ye çevrilir.",
                null=True,
                upload_to="oyun/",
                verbose_name="Logo",
            ),
        ),
        migrations.AddField(
            model_name="kategori",
            name="oyun",
            field=models.BooleanField(
                default=False,
                help_text="İşaretlenirse bayi menüsünde kontörden ayrı “Oyun & Pin” bölümünde görünür. Pin satışında “Yükleme Nereye”yi “Hedef yok”, oyuncu ID ile yüklemede “Oyuncu / hesap numarası” seçin.",
                verbose_name="Oyun / E-pin",
            ),
        ),
    ]
