# Generated by Django 5.2.17 on 2026-09-29 20:01

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


def grup_fiyatlarini_tasi(apps, schema_editor):
    """Eski bayi grubuyla aynı adda kontör grubu açar (oran 0) ve satırı ona bağlar.

    Oran 0 zararsızdır: bayiler kontör grubuna henüz bağlı değil, yönetici
    bağlamadan kimse bu gruptan fiyat almaz. Girilmiş sabit fiyatlar kaybolmaz.
    """
    PaketFiyati = apps.get_model("kontor", "PaketFiyati")
    FiyatGrubu = apps.get_model("kontor", "FiyatGrubu")
    for satir in PaketFiyati.objects.select_related("grup"):
        yeni, _ = FiyatGrubu.objects.get_or_create(ad=satir.grup.ad)
        satir.fiyat_grubu = yeni
        satir.save(update_fields=["fiyat_grubu"])


class Migration(migrations.Migration):

    dependencies = [
        ("kontor", "0005_oyun"),
        ("finans", "0023_alter_bayigrubu_esim_kar_orani"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paket",
            name="satis_fiyati",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Yalnızca kontör fiyat grubu olmayan bayi için (varsayılan grup da yoksa). Gruptaki bayinin fiyatı alıştan hesaplanır.",
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Grupsuz Bayiye Satış",
            ),
        ),
        migrations.CreateModel(
            name="FiyatGrubu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "olusturma_tarihi",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturma Tarihi"
                    ),
                ),
                (
                    "guncelleme_tarihi",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncelleme Tarihi"
                    ),
                ),
                (
                    "ad",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Grup Adı"
                    ),
                ),
                (
                    "oran",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Alış 100 ₺, oran 3 → bayi 103 ₺ öder.",
                        max_digits=6,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Alışın Üstüne (%)",
                    ),
                ),
                (
                    "ek_tutar",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Yüzdenin üstüne her pakete eklenen sabit tutar. Çoğu zaman 0.",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Ek Tutar (₺)",
                    ),
                ),
                (
                    "varsayilan",
                    models.BooleanField(
                        default=False,
                        help_text="Grubu seçilmemiş bayi bu grubun fiyatını öder. Yalnızca bir grup varsayılan olabilir; hiçbiri değilse grupsuz bayi paketin kendi satış fiyatını öder.",
                        verbose_name="Varsayılan",
                    ),
                ),
                (
                    "aciklama",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Açıklama"
                    ),
                ),
            ],
            options={
                "verbose_name": "Kontör Fiyat Grubu",
                "verbose_name_plural": "Kontör Fiyat Grupları",
                "ordering": ["oran", "ek_tutar", "ad"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("varsayilan", True)),
                        fields=("varsayilan",),
                        name="kontor_tek_varsayilan_grup",
                    )
                ],
            },
        ),
        # Grup fiyatları bayi grubundan kontör fiyat grubuna taşınır. FK'nin
        # hedefini doğrudan değiştirmek eski satırları başka tablonun id'sine
        # bağlardı; önce yeni sütun açılır, aynı adla grup kurulup satırlar
        # taşınır, sonra eski sütun düşer.
        migrations.RemoveConstraint(model_name="paketfiyati", name="kontor_paket_grup_fiyat"),
        migrations.AddField(
            model_name="paketfiyati",
            name="fiyat_grubu",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="kontor.fiyatgrubu",
            ),
        ),
        migrations.RunPython(grup_fiyatlarini_tasi, migrations.RunPython.noop),
        migrations.RemoveField(model_name="paketfiyati", name="grup"),
        migrations.RenameField(model_name="paketfiyati", old_name="fiyat_grubu", new_name="grup"),
        migrations.AlterField(
            model_name="paketfiyati",
            name="grup",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="paket_fiyatlari",
                to="kontor.fiyatgrubu",
                verbose_name="Fiyat Grubu",
            ),
        ),
        migrations.AddConstraint(
            model_name="paketfiyati",
            constraint=models.UniqueConstraint(fields=("paket", "grup"), name="kontor_paket_grup_fiyat"),
        ),
    ]
