# Generated by Django 5.2.17 on 2026-09-29 20:52

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kontor", "0009_grup_fiyati_yalnizca_net"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paket",
            name="satis_fiyati",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Yalnızca kontör fiyat grubu olmayan bayi öder (varsayılan grup da yoksa). Bir grubu Fiyat Grupları'nda “Varsayılan” yaparsan bu alan kalkar.",
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Grupsuz Bayiye Satış",
            ),
        ),
    ]
