# Generated by Django 5.2.17 on 2026-09-29 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kontor", "0011_gorulen_sayac_kalkti"),
    ]

    operations = [
        migrations.AddField(
            model_name="deneme",
            name="paket",
            field=models.ForeignKey(
                blank=True,
                help_text="Alternatif gönderildiyse bayinin istediğinden farklıdır. Boşsa işlemin paketi.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="kontor.paket",
                verbose_name="Gönderilen Paket",
            ),
        ),
        migrations.AddField(
            model_name="islem",
            name="plan",
            field=models.JSONField(
                blank=True, editable=False, null=True, verbose_name="Gönderim Planı"
            ),
        ),
        migrations.AddField(
            model_name="paket",
            name="alternatif_yapilmasin",
            field=models.BooleanField(
                default=False,
                help_text="İşaretliyse bu paket istendiğinde yerine ucuz alternatif gönderilmez, başka paketin alternatifi olarak da kullanılmaz.",
                verbose_name="Alternatif yapılmasın",
            ),
        ),
    ]
