# Generated by Django 5.2.17 on 2026-09-30 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kontor", "0012_alternatif_paket"),
    ]

    operations = [
        migrations.AddField(
            model_name="deneme",
            name="saglayici_kaynakli",
            field=models.BooleanField(
                default=False,
                help_text="Ret numaradan değil bizim hesaptan: sağlayıcıda bakiyemiz yetmedi ya da bağlantı kurulamadı. Hiçbir sağlayıcı almazsa işlem iptal değil askıya düşer.",
                verbose_name="Sağlayıcı Tarafında",
            ),
        ),
    ]
