# Generated by Django 5.2.17 on 2026-09-30 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kontor", "0013_deneme_saglayici_kaynakli"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deneme",
            name="saglayici_kaynakli",
            field=models.BooleanField(
                default=False,
                help_text="Gönderim sağlayıcıda hiç açılmadı (kod bulunamadı, bakiye yetmedi, bağlantı kurulamadı). Hiçbir sağlayıcı almazsa işlem iptal değil askıya düşer.",
                verbose_name="Sağlayıcı Tarafında",
            ),
        ),
    ]
