# Generated by Django 5.2.17 on 2026-09-30 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kontor", "0014_deneme_gonderim_reddi"),
    ]

    operations = [
        migrations.AddField(
            model_name="deneme",
            name="gonderim_istegi",
            field=models.TextField(
                blank=True,
                help_text="Sağlayıcıya giden adres ve parametreler; şifre gizlenir.",
                verbose_name="Gönderim İsteği",
            ),
        ),
        migrations.AddField(
            model_name="deneme",
            name="sonuc_istegi",
            field=models.TextField(blank=True, verbose_name="Son Sorgu İsteği"),
        ),
    ]
