# Generated by Django 5.2.17 on 2026-09-30 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kontor", "0015_deneme_istekleri"),
    ]

    operations = [
        migrations.AddField(
            model_name="paket",
            name="sorguda_hep_goster",
            field=models.BooleanField(
                default=False,
                help_text="İşaretliyse numara sorgusu bu paketi döndürmese de bayinin sorgu listesinde çıkar ve numara bu paketi alabilir sayılır (sorguda yok diye iptal edilmez). Operatörün sorgusunda hiç görünmeyen ama her numaraya yüklenen paketler için.",
                verbose_name="Sorguda her zaman göster",
            ),
        ),
    ]
