# Generated by Django 5.2.17 on 2026-09-30 19:39

from django.db import migrations, models


def mevcut_davranisi_koru(apps, schema_editor):
    """Bu alan gelmeden önce sorgu kaynağı seçili her kategoride gönderimden
    önce sorgu yapılıyordu (ucuz alternatif). O kategorilerde açık gelir."""
    Kategori = apps.get_model("kontor", "Kategori")
    Kategori.objects.exclude(sorgu_kaynagi="").update(gonderim_oncesi_sorgu=True)


class Migration(migrations.Migration):

    dependencies = [
        ("kontor", "0016_paket_sorguda_hep_goster"),
    ]

    operations = [
        migrations.AddField(
            model_name="kategori",
            name="gonderim_oncesi_sorgu",
            field=models.BooleanField(
                default=False,
                help_text="Açıksa bayi paket aldığında işlem sağlayıcıya gitmeden önce numara sorgulanır: sorguda aynı içeriği ya da fazlasını daha ucuza veren paket varsa önce o gönderilir (ucuzdan pahalıya); yüklenirse işlem başarılı kapanır, başka paket gönderilmez. Numara ne paketi ne alternatifini alabiliyorsa sağlayıcıya gidilmez, tutar iade edilir. Numara Sorgusu seçili olmalı.",
                verbose_name="Göndermeden önce paket sorgusu",
            ),
        ),
        migrations.RunPython(mevcut_davranisi_koru, migrations.RunPython.noop),
    ]
