# Generated by Django 5.2.17 on 2026-09-30 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kontor", "0017_kategori_gonderim_oncesi_sorgu"),
    ]

    operations = [
        migrations.AddField(
            model_name="paket",
            name="bayiye_gorunur",
            field=models.BooleanField(
                default=True,
                help_text="Kapatılırsa bayi bu paketi listede, numara sorgusunda ve bayi programında görmez, satın alamaz. Aktif kaldığı sürece başka paketin ucuz alternatifi olarak gönderilmeye devam eder. Hiç kullanılmasın isteniyorsa Aktif kapatılır.",
                verbose_name="Bayiye görünür",
            ),
        ),
    ]
