# Generated by Django 5.2.17 on 2026-09-30 21:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kontor", "0018_paket_bayiye_gorunur"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BayiRotasi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sira",
                    models.PositiveSmallIntegerField(default=1, verbose_name="Sıra"),
                ),
                ("aktif", models.BooleanField(default=True, verbose_name="Aktif")),
                (
                    "bayi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kontor_rotalari",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Bayi",
                    ),
                ),
                (
                    "kategori",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bayi_rotalari",
                        to="kontor.kategori",
                        verbose_name="Kategori",
                    ),
                ),
                (
                    "saglayici",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bayi_rotalari",
                        to="kontor.saglayici",
                        verbose_name="Sağlayıcı",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bayiye Özel Sağlayıcı",
                "verbose_name_plural": "Bayiye Özel Sağlayıcılar",
                "ordering": ["bayi", "kategori", "sira", "pk"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("bayi", "kategori", "saglayici"),
                        name="kontor_bayi_rotasi_tekil",
                    )
                ],
            },
        ),
    ]
