# Generated by Django 5.2.17 on 2026-10-09 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kontor", "0021_paylasilan_koda_tutar"),
    ]

    operations = [
        migrations.AddField(
            model_name="kategori",
            name="tam_kontor",
            field=models.BooleanField(
                default=False,
                help_text="Açıksa sağlayıcıya tip olarak “tam” gider: operator=turkcell&amp;tip=ses yerine operator=turkcell&amp;tip=tam. Operatör kodu değişmez; bir paketin sırasında o sağlayıcı için ayrı tip yazılmışsa o gider. Bayi programlarının bu kategoriyi bulduğu kod yine yukarıdaki tip kodudur. Tam kontörde numara sorgusu yapılmaz: bayi ekranında sorgu kutusu çıkmaz, göndermeden önce sorguya gidilmez (alternatifi olmaz).",
                verbose_name="Tam kontör",
            ),
        ),
    ]
