# Generated by Django 5.2.17 on 2026-10-10 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kontor", "0022_kategori_tam_kontor"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="fiyatgrubu",
            options={
                "ordering": ["ad"],
                "verbose_name": "Fiyat Grubu",
                "verbose_name_plural": "Fiyat Grupları",
            },
        ),
    ]
