# Generated by Django 5.2.17 on 2026-10-10 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fatura", "0007_robot_paket_sorgusu"),
        ("kontor", "0023_fiyat_grubu_adi"),
    ]

    operations = [
        migrations.AddField(
            model_name="gorulenpaket",
            name="dakika",
            field=models.PositiveIntegerField(default=0, verbose_name="Dakika"),
        ),
        migrations.AddField(
            model_name="gorulenpaket",
            name="gun",
            field=models.PositiveIntegerField(default=0, verbose_name="Gün"),
        ),
        migrations.AddField(
            model_name="gorulenpaket",
            name="internet_mb",
            field=models.PositiveIntegerField(default=0, verbose_name="İnternet (MB)"),
        ),
        migrations.AddField(
            model_name="gorulenpaket",
            name="sms",
            field=models.PositiveIntegerField(default=0, verbose_name="SMS"),
        ),
        migrations.CreateModel(
            name="RobotSorgusu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "olusturma_tarihi",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturma Tarihi"
                    ),
                ),
                (
                    "guncelleme_tarihi",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncelleme Tarihi"
                    ),
                ),
                ("numara", models.CharField(max_length=10, verbose_name="Numara")),
                ("operator", models.CharField(max_length=20, verbose_name="Operatör")),
                (
                    "durum",
                    models.CharField(
                        choices=[
                            ("bekliyor", "Sırada"),
                            ("sorgulaniyor", "Sorgulanıyor"),
                            ("tamam", "Tamamlandı"),
                            ("hata", "Sorgulanamadı"),
                        ],
                        default="bekliyor",
                        max_length=20,
                        verbose_name="Durum",
                    ),
                ),
                (
                    "alinma_tarihi",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Robot Aldı"
                    ),
                ),
                (
                    "sonuc_tarihi",
                    models.DateTimeField(blank=True, null=True, verbose_name="Sonuç"),
                ),
                (
                    "sonuc",
                    models.JSONField(blank=True, default=dict, verbose_name="Sonuç"),
                ),
                (
                    "mesaj",
                    models.CharField(blank=True, max_length=255, verbose_name="Mesaj"),
                ),
                (
                    "robot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="paket_sorgulari",
                        to="fatura.robot",
                        verbose_name="Robot",
                    ),
                ),
            ],
            options={
                "verbose_name": "Robot Paket Sorgusu",
                "verbose_name_plural": "Robot Paket Sorguları",
                "ordering": ["-olusturma_tarihi"],
                "indexes": [
                    models.Index(
                        fields=["durum", "olusturma_tarihi"],
                        name="kontor_robo_durum_40d119_idx",
                    ),
                    models.Index(
                        fields=["numara", "-olusturma_tarihi"],
                        name="kontor_robo_numara_13d2b3_idx",
                    ),
                ],
            },
        ),
    ]
