# Generated by Django 5.2.17 on 2026-10-10 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kontor", "0024_robot_paket_sorgusu"),
    ]

    operations = [
        migrations.AddField(
            model_name="gorulenpaket",
            name="alis",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Hesaptaki Alış",
            ),
        ),
        migrations.AddField(
            model_name="gorulenpaket",
            name="saglayici",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="gorulen_paketler",
                to="kontor.saglayici",
                verbose_name="Görüldüğü Hesap",
            ),
        ),
        migrations.AddField(
            model_name="gorulenpaket",
            name="saglayici_kodu",
            field=models.CharField(
                blank=True, max_length=60, verbose_name="Sağlayıcıdaki Kodu"
            ),
        ),
    ]
