# Generated by Django 5.2.17 on 2026-10-10 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kontor", "0025_gorulen_paket_hesabi"),
    ]

    operations = [
        migrations.RemoveField(model_name="gorulenpaket", name="alis",),
        migrations.RemoveField(model_name="gorulenpaket", name="saglayici",),
        migrations.RemoveField(model_name="gorulenpaket", name="saglayici_kodu",),
    ]
