# Generated by Django 5.2.17 on 2026-09-03 18:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("basvurular", "0001_initial"),
        ("katalog", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Duyuru",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "olusturma_tarihi",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturma Tarihi"
                    ),
                ),
                (
                    "guncelleme_tarihi",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncelleme Tarihi"
                    ),
                ),
                ("baslik", models.CharField(max_length=200, verbose_name="Başlık")),
                ("icerik", models.TextField(verbose_name="İçerik")),
                (
                    "onemli",
                    models.BooleanField(
                        default=False,
                        help_text="Panelin en üstünde vurgulu gösterilir.",
                        verbose_name="Önemli",
                    ),
                ),
                (
                    "yayin_tarihi",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Yayın Tarihi"
                    ),
                ),
                ("aktif", models.BooleanField(default=True, verbose_name="Aktif")),
            ],
            options={
                "verbose_name": "Duyuru",
                "verbose_name_plural": "3. Duyurular",
                "ordering": ["-onemli", "-olusturma_tarihi"],
            },
        ),
        migrations.CreateModel(
            name="BayiProfili",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "olusturma_tarihi",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturma Tarihi"
                    ),
                ),
                (
                    "guncelleme_tarihi",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncelleme Tarihi"
                    ),
                ),
                (
                    "unvan",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Firma Ünvanı"
                    ),
                ),
                (
                    "yetkili_adi",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Yetkili Adı"
                    ),
                ),
                (
                    "telefon",
                    models.CharField(blank=True, max_length=20, verbose_name="Telefon"),
                ),
                ("adres", models.TextField(blank=True, verbose_name="Adres")),
                (
                    "sehir",
                    models.CharField(blank=True, max_length=80, verbose_name="Şehir"),
                ),
                (
                    "vergi_dairesi",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Vergi Dairesi"
                    ),
                ),
                (
                    "vergi_no",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Vergi / TC No"
                    ),
                ),
                (
                    "notlar",
                    models.TextField(
                        blank=True,
                        help_text="Bayiye gösterilmez.",
                        verbose_name="Notlar",
                    ),
                ),
                (
                    "kullanici",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bayi_profili",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Kullanıcı",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bayi Profili",
                "verbose_name_plural": "1. Bayi Profilleri",
                "ordering": ["kullanici__username"],
            },
        ),
        migrations.CreateModel(
            name="SimKart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "olusturma_tarihi",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturma Tarihi"
                    ),
                ),
                (
                    "guncelleme_tarihi",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncelleme Tarihi"
                    ),
                ),
                (
                    "imei",
                    models.CharField(
                        max_length=40, unique=True, verbose_name="SIM / IMEI"
                    ),
                ),
                (
                    "durum",
                    models.CharField(
                        choices=[
                            ("stokta", "Stokta"),
                            ("kullanildi", "Kullanıldı"),
                            ("arizali", "Arızalı"),
                            ("iade", "İade"),
                        ],
                        default="stokta",
                        max_length=20,
                        verbose_name="Durum",
                    ),
                ),
                (
                    "aciklama",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Açıklama"
                    ),
                ),
                (
                    "basvuru",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sim_kartlar",
                        to="basvurular.basvuru",
                        verbose_name="Kullanıldığı Başvuru",
                    ),
                ),
                (
                    "bayi",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sim_kartlar",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Bayi",
                    ),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sim_kartlar",
                        to="katalog.operator",
                        verbose_name="Operatör",
                    ),
                ),
            ],
            options={
                "verbose_name": "SIM Kart",
                "verbose_name_plural": "2. SIM Kart Stoğu",
                "ordering": ["-olusturma_tarihi"],
                "indexes": [
                    models.Index(
                        fields=["bayi", "durum"], name="bayi_simkar_bayi_id_c588f5_idx"
                    ),
                    models.Index(fields=["imei"], name="bayi_simkar_imei_557237_idx"),
                ],
            },
        ),
    ]
