# Generated by Django 5.2.17 on 2026-09-03 22:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bayi", "0002_alter_simkart_durum"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BayiBasvurusu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "olusturma_tarihi",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturma Tarihi"
                    ),
                ),
                (
                    "guncelleme_tarihi",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncelleme Tarihi"
                    ),
                ),
                ("isim", models.CharField(max_length=100, verbose_name="İsim")),
                ("soyisim", models.CharField(max_length=100, verbose_name="Soyisim")),
                (
                    "irtibat",
                    models.CharField(max_length=20, verbose_name="İrtibat Numarası"),
                ),
                (
                    "durum",
                    models.CharField(
                        choices=[
                            ("yeni", "Yeni"),
                            ("gorusuldu", "Görüşüldü"),
                            ("onaylandi", "Onaylandı"),
                            ("reddedildi", "Reddedildi"),
                        ],
                        default="yeni",
                        max_length=20,
                        verbose_name="Durum",
                    ),
                ),
                (
                    "notlar",
                    models.TextField(
                        blank=True,
                        help_text="Başvurana gösterilmez.",
                        verbose_name="Notlar",
                    ),
                ),
                (
                    "olusturulan_kullanici",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="kaynak_basvurusu",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Açılan Hesap",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bayi Başvurusu",
                "verbose_name_plural": "Bayi Başvuruları",
                "ordering": ["-olusturma_tarihi"],
                "indexes": [
                    models.Index(
                        fields=["durum", "-olusturma_tarihi"],
                        name="bayi_bayiba_durum_f6873b_idx",
                    )
                ],
            },
        ),
    ]
