# Generated by Django 5.2.17 on 2026-09-03 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bayi", "0003_bayibasvurusu"),
    ]

    operations = [
        migrations.AddField(
            model_name="bayiprofili",
            name="bayi_mi",
            field=models.BooleanField(
                default=True,
                help_text="Başvuru girebilir, tamamlanan işlemlerden hakediş alır.",
                verbose_name="Bayi",
            ),
        ),
        migrations.AddField(
            model_name="bayiprofili",
            name="tedarikci_mi",
            field=models.BooleanField(
                default=False,
                help_text="Kendisine atanan işlemleri satın alır; bedeli hesabından düşülür.",
                verbose_name="Tedarikçi",
            ),
        ),
    ]
