# Generated by Django 5.2.17 on 2026-09-04 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bayi", "0004_bayiprofili_bayi_mi_bayiprofili_tedarikci_mi"),
    ]

    operations = [
        migrations.AddField(
            model_name="bayibasvurusu",
            name="parola_ozeti",
            field=models.CharField(
                blank=True,
                editable=False,
                help_text="Başvuran kendi parolasını seçer. Burada yalnızca özeti durur; düz metin hiçbir yerde saklanmaz ve kimse göremez.",
                max_length=128,
                verbose_name="Parola Özeti",
            ),
        ),
    ]
