# Generated by Django 5.2.17 on 2026-09-05 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bayi", "0005_bayibasvurusu_parola_ozeti"),
        ("finans", "0008_remove_ucretkurali_kampanya"),
    ]

    operations = [
        migrations.AddField(
            model_name="bayibasvurusu",
            name="bayi_grubu",
            field=models.ForeignKey(
                blank=True,
                help_text="Hesap açılırken cüzdana yazılır. Bayinin hangi fiyat listesinden hakediş alacağını bu belirler; başvurana sorulmaz, yönetim seçer.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bayi_basvurulari",
                to="finans.bayigrubu",
                verbose_name="Fiyat Kademesi",
            ),
        ),
    ]
