# Generated by Django 5.2.17 on 2026-09-05 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bayi", "0007_detay_gorunum_tercihi"),
    ]

    operations = [
        migrations.AddField(
            model_name="detaygorunumtercihi",
            name="admin_gizli_alanlar",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Başvuru detayında bu kullanıcıya gösterilmeyecek alanlar. Yalnızca görünümü etkiler; gizlenen alanın değeri korunur.",
                verbose_name="Yönetim Panelinde Gizlenen Alanlar",
            ),
        ),
    ]
