# Generated by Django 5.2.17 on 2026-09-05 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bayi", "0008_admin_gorunum_tercihi"),
        ("katalog", "0015_tarife_bayiye_gorunur"),
    ]

    operations = [
        migrations.AlterField(
            model_name="simkart",
            name="operator",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sim_kartlar",
                to="katalog.operator",
                verbose_name="Operatör",
            ),
        ),
    ]
