# Generated by Django 5.2.17 on 2026-09-06 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bayi", "0009_alter_simkart_operator"),
    ]

    operations = [
        migrations.CreateModel(
            name="GenelAyarlar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "olusturma_tarihi",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturma Tarihi"
                    ),
                ),
                (
                    "guncelleme_tarihi",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncelleme Tarihi"
                    ),
                ),
                (
                    "telefon",
                    models.CharField(
                        blank=True,
                        help_text="Sitede tıklanabilir olarak görünür. Örn: 0850 123 45 67",
                        max_length=30,
                        verbose_name="İletişim Telefonu",
                    ),
                ),
                (
                    "eposta",
                    models.EmailField(
                        blank=True,
                        help_text="Sitede tıklanabilir olarak görünür.",
                        max_length=254,
                        verbose_name="İletişim E-postası",
                    ),
                ),
            ],
            options={
                "verbose_name": "Genel Ayar",
                "verbose_name_plural": "Genel Ayarlar",
            },
        ),
    ]
