# Generated by Django 5.2.17 on 2026-09-07 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bayi", "0010_genelayarlar"),
        ("katalog", "0015_tarife_bayiye_gorunur"),
    ]

    operations = [
        migrations.AddField(
            model_name="bayiprofili",
            name="kapali_kategoriler",
            field=models.ManyToManyField(
                blank=True,
                help_text="İşaretlenen tip bu bayiye hiç gösterilmez: kategori ekranında, panelde, tarife kataloğunda ve hakediş sayfasında çıkmaz; adresini elle yazsa da form açılmaz. Boş bırakılırsa hepsi açıktır.",
                related_name="kapali_bayiler",
                to="katalog.basvurukategorisi",
                verbose_name="Bu bayiye kapalı başvuru tipleri",
            ),
        ),
    ]
