# Generated by Django 5.2.17 on 2026-09-11 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bayi", "0011_bayiprofili_kapali_kategoriler"),
    ]

    operations = [
        migrations.AddField(
            model_name="genelayarlar",
            name="usd_kuru",
            field=models.DecimalField(
                decimal_places=4,
                default=0,
                help_text="1 dolar kaç lira. eSIM paketlerinin satış fiyatı bu kurla hesaplanır; sıfırsa eSIM satışı kapalıdır. eSIM paket listesindeki düğme TCMB'den çeker.",
                max_digits=10,
                verbose_name="USD Kuru (₺)",
            ),
        ),
        migrations.AddField(
            model_name="genelayarlar",
            name="usd_kuru_tarihi",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Kur Güncelleme Tarihi"
            ),
        ),
    ]
