# Generated by Django 5.2.17 on 2026-09-11 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bayi", "0012_genelayarlar_usd_kuru_genelayarlar_usd_kuru_tarihi"),
    ]

    operations = [
        migrations.AddField(
            model_name="genelayarlar",
            name="esim_tavsiye_kar_orani",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Bayiye “müşteriye şu fiyata sat” diye gösterilen rakam: bayinin bizden aldığı fiyat × (1 + bu yüzde), küsurat atılır. 0 ise tavsiye fiyatı gösterilmez.",
                max_digits=6,
                verbose_name="eSIM Tavsiye Edilen Satış Kâr Oranı (%)",
            ),
        ),
    ]
