# Generated by Django 5.2.17 on 2026-09-13 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bayi", "0013_genelayarlar_esim_tavsiye_kar_orani"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="genelayarlar", name="esim_tavsiye_kar_orani",
        ),
    ]
