# Generated by Django 5.2.17 on 2026-09-21 21:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bayi", "0014_remove_genelayarlar_esim_tavsiye_kar_orani"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="simkart",
            name="ariza_bildiren",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Arızayı Bildiren",
            ),
        ),
        migrations.AddField(
            model_name="simkart",
            name="ariza_tarihi",
            field=models.DateTimeField(
                blank=True,
                editable=False,
                null=True,
                verbose_name="Arızalı İşaretlendi",
            ),
        ),
        migrations.AddField(
            model_name="simkart",
            name="degisim_tarihi",
            field=models.DateTimeField(
                blank=True,
                help_text="Operatörün bozuk kartın yerine verdiği kartın geldiği gün. Yeni kart ayrıca kayıt açılmaz; “Toplu ekle” ile stoğa girer.",
                null=True,
                verbose_name="Operatörden Değişimi Geldi",
            ),
        ),
        migrations.AddField(
            model_name="simkart",
            name="iade_alinma_tarihi",
            field=models.DateTimeField(
                blank=True,
                help_text="Bozuk kartın elimize geçtiği gün. Boşsa kart hâlâ bayide.",
                null=True,
                verbose_name="Bayiden Alındı",
            ),
        ),
        migrations.AddField(
            model_name="simkart",
            name="yerine_verilen",
            field=models.OneToOneField(
                blank=True,
                help_text="Bayiye bu kartın yerine stoktan zimmetlenen kart.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="yerine_gectigi",
                to="bayi.simkart",
                verbose_name="Yerine Verilen Kart",
            ),
        ),
    ]
