# Generated by Django 5.2.17 on 2026-09-30 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bayi", "0015_simkart_ariza_takibi"),
    ]

    operations = [
        migrations.AddField(
            model_name="genelayarlar",
            name="proxy_api_anahtari",
            field=models.CharField(
                blank=True,
                help_text="Doluysa operatör numara sorguları her seferinde listeden rastgele seçilen bir proxy üzerinden yapılır. Boşsa sorgu doğrudan sunucudan gider.",
                max_length=200,
                verbose_name="Proxy API anahtarı",
            ),
        ),
    ]
