# Generated by Django 5.2.17 on 2026-09-03 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Operator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "olusturma_tarihi",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturma Tarihi"
                    ),
                ),
                (
                    "guncelleme_tarihi",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncelleme Tarihi"
                    ),
                ),
                (
                    "ad",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Operatör Adı"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=120, unique=True, verbose_name="Kısa Ad"
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="operator/",
                        verbose_name="Logo",
                    ),
                ),
                (
                    "renk",
                    models.CharField(
                        default="#6366f1",
                        help_text="Panelde rozet rengi olarak kullanılır. Örn: #e30613",
                        max_length=7,
                        verbose_name="Marka Rengi",
                    ),
                ),
                ("sira", models.PositiveIntegerField(default=0, verbose_name="Sıra")),
                ("aktif", models.BooleanField(default=True, verbose_name="Aktif")),
            ],
            options={
                "verbose_name": "Operatör",
                "verbose_name_plural": "Operatörler",
                "ordering": ["sira", "ad"],
            },
        ),
        migrations.CreateModel(
            name="BasvuruKategorisi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "olusturma_tarihi",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturma Tarihi"
                    ),
                ),
                (
                    "guncelleme_tarihi",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncelleme Tarihi"
                    ),
                ),
                (
                    "ad",
                    models.CharField(
                        max_length=150, unique=True, verbose_name="Kategori Adı"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=170, unique=True, verbose_name="Kısa Ad"
                    ),
                ),
                ("aciklama", models.TextField(blank=True, verbose_name="Açıklama")),
                (
                    "ikon",
                    models.CharField(
                        default="description",
                        help_text="Material Symbols ikon adı. Örn: sim_card, router, swap_horiz",
                        max_length=50,
                        verbose_name="İkon",
                    ),
                ),
                (
                    "musteri_tipi",
                    models.CharField(
                        choices=[
                            ("turk", "Türk Vatandaşı"),
                            ("yabanci", "Yabancı Uyruklu"),
                            ("hepsi", "Her İkisi"),
                        ],
                        default="hepsi",
                        max_length=10,
                        verbose_name="Müşteri Tipi",
                    ),
                ),
                (
                    "tarife_zorunlu",
                    models.BooleanField(
                        default=True,
                        help_text="Pasaportlu işlemler gibi tarifesiz kategorilerde kapatın.",
                        verbose_name="Tarife Seçimi Zorunlu",
                    ),
                ),
                ("sira", models.PositiveIntegerField(default=0, verbose_name="Sıra")),
                ("aktif", models.BooleanField(default=True, verbose_name="Aktif")),
                (
                    "operatorler",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Boş bırakılırsa tüm aktif operatörler seçilebilir.",
                        related_name="kategoriler",
                        to="katalog.operator",
                        verbose_name="Geçerli Operatörler",
                    ),
                ),
            ],
            options={
                "verbose_name": "Başvuru Kategorisi",
                "verbose_name_plural": "Başvuru Kategorileri",
                "ordering": ["sira", "ad"],
            },
        ),
        migrations.CreateModel(
            name="Tarife",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "olusturma_tarihi",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturma Tarihi"
                    ),
                ),
                (
                    "guncelleme_tarihi",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncelleme Tarihi"
                    ),
                ),
                ("ad", models.CharField(max_length=200, verbose_name="Tarife Adı")),
                (
                    "musteri_tipi",
                    models.CharField(
                        choices=[
                            ("turk", "Türk Vatandaşı"),
                            ("yabanci", "Yabancı Uyruklu"),
                            ("hepsi", "Her İkisi"),
                        ],
                        default="hepsi",
                        max_length=10,
                        verbose_name="Müşteri Tipi",
                    ),
                ),
                ("aciklama", models.TextField(blank=True, verbose_name="Açıklama")),
                ("sira", models.PositiveIntegerField(default=0, verbose_name="Sıra")),
                ("aktif", models.BooleanField(default=True, verbose_name="Aktif")),
                (
                    "kategori",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tarifeler",
                        to="katalog.basvurukategorisi",
                        verbose_name="Kategori",
                    ),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tarifeler",
                        to="katalog.operator",
                        verbose_name="Operatör",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tarife",
                "verbose_name_plural": "Tarifeler",
                "ordering": ["kategori", "operator", "sira", "ad"],
            },
        ),
        migrations.CreateModel(
            name="Kampanya",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "olusturma_tarihi",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturma Tarihi"
                    ),
                ),
                (
                    "guncelleme_tarihi",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncelleme Tarihi"
                    ),
                ),
                ("ad", models.CharField(max_length=200, verbose_name="Kampanya Adı")),
                ("aciklama", models.TextField(blank=True, verbose_name="Açıklama")),
                (
                    "baslangic_tarihi",
                    models.DateField(
                        blank=True, null=True, verbose_name="Başlangıç Tarihi"
                    ),
                ),
                (
                    "bitis_tarihi",
                    models.DateField(
                        blank=True, null=True, verbose_name="Bitiş Tarihi"
                    ),
                ),
                ("sira", models.PositiveIntegerField(default=0, verbose_name="Sıra")),
                ("aktif", models.BooleanField(default=True, verbose_name="Aktif")),
                (
                    "tarife",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kampanyalar",
                        to="katalog.tarife",
                        verbose_name="Tarife",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kampanya",
                "verbose_name_plural": "Kampanyalar",
                "ordering": ["tarife", "sira", "ad"],
            },
        ),
        migrations.CreateModel(
            name="KategoriAlani",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "olusturma_tarihi",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturma Tarihi"
                    ),
                ),
                (
                    "guncelleme_tarihi",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncelleme Tarihi"
                    ),
                ),
                (
                    "kod",
                    models.SlugField(
                        help_text="Veride saklanacak anahtar. Örn: sim_imei, modem_istegi",
                        max_length=60,
                        verbose_name="Alan Kodu",
                    ),
                ),
                ("etiket", models.CharField(max_length=150, verbose_name="Etiket")),
                (
                    "tip",
                    models.CharField(
                        choices=[
                            ("metin", "Metin"),
                            ("uzun_metin", "Uzun Metin"),
                            ("sayi", "Sayı"),
                            ("tutar", "Tutar"),
                            ("tarih", "Tarih"),
                            ("telefon", "Telefon"),
                            ("eposta", "E-posta"),
                            ("secim", "Açılır Liste"),
                            ("onay", "Evet / Hayır"),
                            ("dosya", "Dosya"),
                            ("resim", "Resim"),
                        ],
                        default="metin",
                        max_length=20,
                        verbose_name="Alan Tipi",
                    ),
                ),
                (
                    "grup",
                    models.CharField(
                        blank=True,
                        help_text="Aynı başlığı taşıyan alanlar formda birlikte gruplanır.",
                        max_length=100,
                        verbose_name="Bölüm Başlığı",
                    ),
                ),
                ("zorunlu", models.BooleanField(default=False, verbose_name="Zorunlu")),
                (
                    "yardim_metni",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Yardım Metni"
                    ),
                ),
                (
                    "placeholder",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Placeholder"
                    ),
                ),
                (
                    "secenekler",
                    models.TextField(
                        blank=True,
                        help_text="Açılır liste için her satıra bir seçenek yazın.",
                        verbose_name="Seçenekler",
                    ),
                ),
                (
                    "dogrulama_deseni",
                    models.CharField(
                        blank=True,
                        help_text="Opsiyonel regex. Örn: ^[0-9]{11}$",
                        max_length=255,
                        verbose_name="Doğrulama Deseni",
                    ),
                ),
                (
                    "min_uzunluk",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Min. Uzunluk"
                    ),
                ),
                (
                    "max_uzunluk",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Maks. Uzunluk"
                    ),
                ),
                (
                    "kosul_degeri",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Koşul Değeri"
                    ),
                ),
                ("sira", models.PositiveIntegerField(default=0, verbose_name="Sıra")),
                ("aktif", models.BooleanField(default=True, verbose_name="Aktif")),
                (
                    "kategori",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alanlar",
                        to="katalog.basvurukategorisi",
                        verbose_name="Kategori",
                    ),
                ),
                (
                    "kosul_alani",
                    models.ForeignKey(
                        blank=True,
                        help_text="Bu alan yalnızca seçilen alan belirli bir değerdeyse görünür.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="kosullu_alanlar",
                        to="katalog.kategorialani",
                        verbose_name="Koşul Alanı",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kategori Alanı",
                "verbose_name_plural": "Kategori Form Alanları",
                "ordering": ["kategori", "sira", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("kategori", "kod"), name="kategori_alan_kodu_benzersiz"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="tarife",
            constraint=models.UniqueConstraint(
                fields=("kategori", "operator", "ad"),
                name="tarife_kategori_operator_ad_benzersiz",
            ),
        ),
    ]
