# Generated by Django 5.2.17 on 2026-09-03 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("katalog", "0002_turkce_sluglari_duzelt"),
    ]

    operations = [
        migrations.AddField(
            model_name="kategorialani",
            name="cekirdek_alan",
            field=models.CharField(
                blank=True,
                choices=[
                    ("isim", "İsim"),
                    ("soyisim", "Soyisim"),
                    ("kimlik_tipi", "Kimlik Tipi"),
                    ("kimlik_no", "Kimlik / Pasaport No"),
                    ("irtibat", "İletişim Numarası"),
                    ("numara", "İşlem Yapılacak Numara"),
                    ("adres", "Adres"),
                ],
                help_text="Doldurulursa değer başvurunun kendi kolonuna yazılır ve aranabilir olur. Boş bırakılırsa alan bu kategoriye özel ek bilgi olarak saklanır.",
                max_length=20,
                verbose_name="Çekirdek Alan",
            ),
        ),
        migrations.AddConstraint(
            model_name="kategorialani",
            constraint=models.UniqueConstraint(
                condition=models.Q(("cekirdek_alan__gt", "")),
                fields=("kategori", "cekirdek_alan"),
                name="kategori_cekirdek_alan_benzersiz",
            ),
        ),
    ]
