# Generated by Django 5.2.17 on 2026-09-03 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("katalog", "0003_kategorialani_cekirdek_alan_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kategorialani",
            name="tip",
            field=models.CharField(
                choices=[
                    ("metin", "Metin"),
                    ("uzun_metin", "Uzun Metin"),
                    ("sayi", "Sayı"),
                    ("tutar", "Tutar"),
                    ("tarih", "Tarih"),
                    ("telefon", "Telefon"),
                    ("eposta", "E-posta"),
                    ("secim", "Açılır Liste"),
                    ("onay", "Evet / Hayır"),
                    ("dosya", "Dosya"),
                    ("resim", "Resim"),
                    ("sim_kart", "SIM Kart (bayinin stoğundan)"),
                ],
                default="metin",
                max_length=20,
                verbose_name="Alan Tipi",
            ),
        ),
    ]
