# Generated by Django 5.2.17 on 2026-09-03 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("katalog", "0004_alter_kategorialani_tip"),
    ]

    operations = [
        migrations.AddField(
            model_name="kampanya",
            name="gorsel",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="kampanya/%Y/%m/",
                verbose_name="Görsel",
            ),
        ),
        migrations.AddField(
            model_name="tarife",
            name="gorsel",
            field=models.ImageField(
                blank=True,
                help_text="Operatörün tarife görseli. Bayi tarife sayfasında gösterilir.",
                null=True,
                upload_to="tarife/%Y/%m/",
                verbose_name="Görsel",
            ),
        ),
        migrations.AlterField(
            model_name="kampanya",
            name="aciklama",
            field=models.TextField(
                blank=True,
                help_text="Bayi tarife sayfasında görünür.",
                verbose_name="Açıklama",
            ),
        ),
        migrations.AlterField(
            model_name="tarife",
            name="aciklama",
            field=models.TextField(
                blank=True,
                help_text="Bayi tarife sayfasında bu tarifenin altında görünür.",
                verbose_name="Açıklama",
            ),
        ),
    ]
