# Generated by Django 5.2.17 on 2026-09-04 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("katalog", "0005_kampanya_gorsel_tarife_gorsel_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="basvurukategorisi",
            name="sim_karsiligi_gerekir",
            field=models.BooleanField(
                default=False,
                help_text="Bu tip aktivasyon fiziksel SIM tüketiyorsa açın. Tamamlanan her işlem için operatörden alınacak yeni SIM takibe girer.",
                verbose_name="SIM Karşılığı Takip Edilsin",
            ),
        ),
    ]
