# Generated by Django 5.2.17 on 2026-09-04 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("basvurular", "0009_remove_basvuru_kampanya"),
        ("finans", "0008_remove_ucretkurali_kampanya"),
        ("katalog", "0006_basvurukategorisi_sim_karsiligi_gerekir"),
    ]

    operations = [
        migrations.DeleteModel(name="Kampanya",),
    ]
