# Generated by Django 5.2.17 on 2026-09-05 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("katalog", "0007_delete_kampanya"),
    ]

    operations = [
        migrations.CreateModel(
            name="Kampanya",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "olusturma_tarihi",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturma Tarihi"
                    ),
                ),
                (
                    "guncelleme_tarihi",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncelleme Tarihi"
                    ),
                ),
                ("ad", models.CharField(max_length=200, verbose_name="Kampanya Adı")),
                (
                    "aciklama",
                    models.TextField(
                        blank=True,
                        help_text="Bayi tarife sayfasında görünür.",
                        verbose_name="Açıklama",
                    ),
                ),
                (
                    "gorsel",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="kampanya/%Y/%m/",
                        verbose_name="Görsel",
                    ),
                ),
                (
                    "baslangic_tarihi",
                    models.DateField(
                        blank=True, null=True, verbose_name="Başlangıç Tarihi"
                    ),
                ),
                (
                    "bitis_tarihi",
                    models.DateField(
                        blank=True, null=True, verbose_name="Bitiş Tarihi"
                    ),
                ),
                ("sira", models.PositiveIntegerField(default=0, verbose_name="Sıra")),
                ("aktif", models.BooleanField(default=True, verbose_name="Aktif")),
                (
                    "tarife",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kampanyalar",
                        to="katalog.tarife",
                        verbose_name="Tarife",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kampanya",
                "verbose_name_plural": "Kampanyalar",
                "ordering": ["tarife", "sira", "ad"],
            },
        ),
    ]
