# Generated by Django 5.2.17 on 2026-09-05 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("katalog", "0008_kampanya"),
    ]

    operations = [
        migrations.RemoveField(model_name="kampanya", name="aciklama",),
        migrations.RemoveField(model_name="kampanya", name="gorsel",),
    ]
