# Generated by Django 5.2.17 on 2026-09-05 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("katalog", "0009_remove_kampanya_aciklama_remove_kampanya_gorsel"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tarife",
            options={
                "ordering": ["operator", "sira", "ad"],
                "verbose_name": "Tarife",
                "verbose_name_plural": "Tarifeler",
            },
        ),
        migrations.RemoveConstraint(
            model_name="tarife", name="tarife_kategori_operator_ad_benzersiz",
        ),
        migrations.AddField(
            model_name="tarife",
            name="kategoriler",
            field=models.ManyToManyField(
                help_text="Aynı tarife birden çok kategoride geçerli olabilir. Operatör aynı paketi hem numara taşımada hem yeni hatta veriyorsa hepsini işaretleyin; tarifeyi ikinci kez açmak gerekmez.",
                related_name="tarifeler",
                to="katalog.basvurukategorisi",
                verbose_name="Kategoriler",
            ),
        ),
        migrations.AlterField(
            model_name="tarife",
            name="kategori",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="eski_tarifeler",
                to="katalog.basvurukategorisi",
                verbose_name="Kategori",
            ),
        ),
        migrations.AddConstraint(
            model_name="tarife",
            constraint=models.UniqueConstraint(
                fields=("operator", "ad"), name="tarife_operator_ad_benzersiz"
            ),
        ),
    ]
