# Generated by Django 5.2.17 on 2026-09-05 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("katalog", "0011_tarife_kategorilerini_tasi"),
    ]

    operations = [
        migrations.RemoveField(model_name="tarife", name="kategori",),
    ]
