# Generated by Django 5.2.17 on 2026-09-05 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("katalog", "0012_tarife_tekil_kategoriyi_kaldir"),
    ]

    operations = [
        migrations.AddField(
            model_name="tarife",
            name="kisa_aciklama",
            field=models.CharField(
                blank=True,
                help_text="Bayi bu tarifeyi başvuruda seçtiği anda karşısına açılır. Atlanmaması gereken bir şey varsa buraya yazın; boş bırakılırsa hiçbir şey açılmaz.",
                max_length=300,
                verbose_name="Kısa Açıklama / Uyarı",
            ),
        ),
    ]
