# Generated by Django 5.2.17 on 2026-09-05 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("katalog", "0013_tarife_kisa_aciklama"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kategorialani",
            name="aktif",
            field=models.BooleanField(
                default=True,
                help_text="Kapatılırsa alan formda hiç sorulmaz. Bu kategoride gereksiz alanları silmek yerine kapatın; eski başvurulardaki değerleri durur.",
                verbose_name="Aktif",
            ),
        ),
        migrations.AlterField(
            model_name="kategorialani",
            name="dogrulama_deseni",
            field=models.CharField(
                blank=True,
                help_text="İsteğe bağlı. Girilen değer bu kalıba uymazsa form reddedilir. Örn: 11 hane rakam için ^[0-9]{11}$",
                max_length=255,
                verbose_name="Doğrulama Deseni",
            ),
        ),
        migrations.AlterField(
            model_name="kategorialani",
            name="etiket",
            field=models.CharField(
                help_text="Bayinin formda gördüğü başlık. Başvuru detayında ve yönetim panelinde de bu ad görünür. Örn: Kimlik Ön Yüz",
                max_length=150,
                verbose_name="Etiket",
            ),
        ),
        migrations.AlterField(
            model_name="kategorialani",
            name="grup",
            field=models.CharField(
                blank=True,
                help_text="Formda başlık olarak çıkar; aynı başlığı taşıyan alanlar birlikte gruplanır. Boş bırakılırsa alan “Başvuru detayları” altına düşer. Kimlik görselleri için “Belgeler” yazın.",
                max_length=100,
                verbose_name="Bölüm Başlığı",
            ),
        ),
        migrations.AlterField(
            model_name="kategorialani",
            name="kod",
            field=models.SlugField(
                help_text="Verinin saklanacağı anahtar; bayiye gösterilmez. Kategoride benzersiz olmalı. Türkçe harf ve boşluk kullanmayın. Örn: sim_imei, kimlik_on_cocuk",
                max_length=60,
                verbose_name="Alan Kodu",
            ),
        ),
        migrations.AlterField(
            model_name="kategorialani",
            name="kosul_alani",
            field=models.ForeignKey(
                blank=True,
                help_text="Bu alan formda hep görünmesin, yalnızca başka bir alan belirli bir değerdeyken çıksın istiyorsanız o alanı seçin. Boşsa alan her zaman görünür.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="kosullu_alanlar",
                to="katalog.kategorialani",
                verbose_name="Koşul Alanı",
            ),
        ),
        migrations.AlterField(
            model_name="kategorialani",
            name="kosul_degeri",
            field=models.CharField(
                blank=True,
                help_text="Koşul alanı bu değerdeyken bu alan görünür.",
                max_length=150,
                verbose_name="Koşul Değeri",
            ),
        ),
        migrations.AlterField(
            model_name="kategorialani",
            name="max_uzunluk",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Kutuya bu sayıdan fazla karakter yazılamaz.",
                null=True,
                verbose_name="Maks. Uzunluk",
            ),
        ),
        migrations.AlterField(
            model_name="kategorialani",
            name="min_uzunluk",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Girilen metin bu kadar karakterden kısaysa form reddedilir.",
                null=True,
                verbose_name="Min. Uzunluk",
            ),
        ),
        migrations.AlterField(
            model_name="kategorialani",
            name="placeholder",
            field=models.CharField(
                blank=True,
                help_text="Kutu boşken içinde soluk görünen örnek metin. Yazılınca kaybolur; yardım metninin yerini tutmaz.",
                max_length=150,
                verbose_name="Placeholder",
            ),
        ),
        migrations.AlterField(
            model_name="kategorialani",
            name="secenekler",
            field=models.TextField(
                blank=True,
                help_text="Yalnızca Seçim tipinde kullanılır: her satıra bir seçenek yazın. Bayi bunlardan birini seçer.",
                verbose_name="Seçenekler",
            ),
        ),
        migrations.AlterField(
            model_name="kategorialani",
            name="sira",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Formdaki yeri. Küçük sayı önce gelir.",
                verbose_name="Sıra",
            ),
        ),
        migrations.AlterField(
            model_name="kategorialani",
            name="tip",
            field=models.CharField(
                choices=[
                    ("metin", "Metin"),
                    ("uzun_metin", "Uzun Metin"),
                    ("sayi", "Sayı"),
                    ("tutar", "Tutar"),
                    ("tarih", "Tarih"),
                    ("telefon", "Telefon"),
                    ("eposta", "E-posta"),
                    ("secim", "Açılır Liste"),
                    ("onay", "Evet / Hayır"),
                    ("dosya", "Dosya"),
                    ("resim", "Resim"),
                    ("sim_kart", "SIM Kart (bayinin stoğundan)"),
                ],
                default="metin",
                help_text="Formda hangi kutunun çıkacağı. Resim seçilirse telefonda doğrudan kamera açılır; SIM Kart seçilirse bayinin stoğundaki kartlar listelenir. Resim ve Dosya alanları çekirdek alan olamaz.",
                max_length=20,
                verbose_name="Alan Tipi",
            ),
        ),
        migrations.AlterField(
            model_name="kategorialani",
            name="yardim_metni",
            field=models.CharField(
                blank=True,
                help_text="Formda kutunun altında küçük gri yazı olarak görünür.",
                max_length=255,
                verbose_name="Yardım Metni",
            ),
        ),
        migrations.AlterField(
            model_name="kategorialani",
            name="zorunlu",
            field=models.BooleanField(
                default=False,
                help_text="Açıksa bayi bu alanı doldurmadan başvuruyu gönderemez.",
                verbose_name="Zorunlu",
            ),
        ),
    ]
