# Generated by Django 5.2.17 on 2026-09-05 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("katalog", "0014_alan_yardim_metinleri"),
    ]

    operations = [
        migrations.AddField(
            model_name="tarife",
            name="bayiye_gorunur",
            field=models.BooleanField(
                default=True,
                help_text="Kapalıysa tarife bayinin Tarifeler kataloğunda listelenmez ama başvuruda hâlâ seçilebilir. Bayinin hiç seçememesi gerekiyorsa “Aktif”i kapatın.",
                verbose_name="Bayiye Görünür",
            ),
        ),
        migrations.AlterField(
            model_name="tarife",
            name="aktif",
            field=models.BooleanField(
                default=True,
                help_text="Kapatılırsa tarife hiçbir yerde çıkmaz: ne katalogda ne başvuru formunda. Eski başvurular ve fiyat kuralları yerinde kalır.",
                verbose_name="Aktif",
            ),
        ),
        migrations.AlterField(
            model_name="tarife",
            name="sira",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Listedeki yeri. Küçük sayı önce gelir.",
                verbose_name="Sıra",
            ),
        ),
    ]
