# Generated by Django 5.2.17 on 2026-09-08 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("katalog", "0015_tarife_bayiye_gorunur"),
    ]

    operations = [
        migrations.AddField(
            model_name="kategorialani",
            name="tarifeler",
            field=models.ManyToManyField(
                blank=True,
                help_text="Boş bırakılırsa alan kategorideki bütün tarifelerde sorulur. Tarife işaretlenirse koşul <b>kategori ve tarife</b> olarak birlikte aranır: alan yalnızca bu tarifelerden biri seçildiğinde çıkar.",
                related_name="kategori_alanlari",
                to="katalog.tarife",
                verbose_name="Yalnızca Bu Tarifelerde",
            ),
        ),
    ]
