# Generated by Django 5.2.17 on 2026-09-08 18:07

import apps.magaza.models
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Urun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "olusturma_tarihi",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturma Tarihi"
                    ),
                ),
                (
                    "guncelleme_tarihi",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncelleme Tarihi"
                    ),
                ),
                (
                    "ad",
                    models.CharField(
                        max_length=200, unique=True, verbose_name="Ürün Adı"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=220, unique=True, verbose_name="Kısa Ad"
                    ),
                ),
                (
                    "aciklama",
                    models.TextField(
                        blank=True,
                        help_text="Bayi ürün sayfasında görür. Kutu içeriği, model, renk…",
                        verbose_name="Açıklama",
                    ),
                ),
                (
                    "gorsel",
                    models.ImageField(
                        blank=True,
                        help_text="Mağaza listesinde ve ürün sayfasında gösterilir.",
                        null=True,
                        upload_to="urun/%Y/%m/",
                        verbose_name="Görsel",
                    ),
                ),
                (
                    "fiyat",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Bayinin bakiyesinden düşülecek tutar.",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Satış Fiyatı",
                    ),
                ),
                (
                    "sira",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Mağazadaki yeri. Küçük sayı önce gelir.",
                        verbose_name="Sıra",
                    ),
                ),
                (
                    "aktif",
                    models.BooleanField(
                        default=True,
                        help_text="Kapatılırsa ürün mağazada hiç görünmez ve sipariş edilemez. Verilmiş siparişler yerinde kalır.",
                        verbose_name="Aktif",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ürün",
                "verbose_name_plural": "Ürünler",
                "ordering": ["sira", "ad"],
            },
        ),
        migrations.CreateModel(
            name="Siparis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "olusturma_tarihi",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturma Tarihi"
                    ),
                ),
                (
                    "guncelleme_tarihi",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncelleme Tarihi"
                    ),
                ),
                (
                    "referans_no",
                    models.CharField(
                        default=apps.magaza.models.referans_no_uret,
                        editable=False,
                        max_length=12,
                        unique=True,
                        verbose_name="Referans No",
                    ),
                ),
                ("urun_adi", models.CharField(max_length=200, verbose_name="Ürün Adı")),
                (
                    "adet",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Adet",
                    ),
                ),
                (
                    "birim_fiyat",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Birim Fiyat"
                    ),
                ),
                (
                    "tutar",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Toplam Tutar"
                    ),
                ),
                (
                    "durum",
                    models.CharField(
                        choices=[
                            ("verildi", "Sipariş verildi"),
                            ("teslim", "Teslim edildi"),
                            ("iptal", "İptal edildi"),
                        ],
                        default="verildi",
                        max_length=20,
                        verbose_name="Durum",
                    ),
                ),
                (
                    "bayi_notu",
                    models.CharField(
                        blank=True,
                        help_text="Bayinin sipariş verirken yazdığı not.",
                        max_length=255,
                        verbose_name="Bayi Notu",
                    ),
                ),
                (
                    "yonetim_notu",
                    models.CharField(
                        blank=True,
                        help_text="Bayi sipariş listesinde görür. İptal sebebi buraya yazılır.",
                        max_length=255,
                        verbose_name="Yönetim Notu",
                    ),
                ),
                (
                    "para_islendi",
                    models.BooleanField(
                        default=False, editable=False, verbose_name="Para İşlendi"
                    ),
                ),
                (
                    "para_surumu",
                    models.PositiveIntegerField(
                        default=0,
                        editable=False,
                        help_text="Sipariş her iptal edildiğinde artar. Defterdeki tekillik anahtarı bu sayıyı içerir; iptal edilip yeniden açılan siparişin ikinci hareketi aynı anahtara çarpıp sessizce yutulmasın.",
                        verbose_name="Para İşlem Sürümü",
                    ),
                ),
                (
                    "islem_anahtari",
                    models.CharField(
                        blank=True,
                        editable=False,
                        help_text="Sipariş formunda gizli alanda taşınır: sayfa yenilenince aynı sipariş ikinci kez açılmaz.",
                        max_length=64,
                        null=True,
                        unique=True,
                        verbose_name="İşlem Anahtarı",
                    ),
                ),
                (
                    "bayi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="siparisler",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Bayi",
                    ),
                ),
                (
                    "urun",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="siparisler",
                        to="magaza.urun",
                        verbose_name="Ürün",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sipariş",
                "verbose_name_plural": "Siparişler",
                "ordering": ["-olusturma_tarihi"],
                "indexes": [
                    models.Index(
                        fields=["durum", "-olusturma_tarihi"],
                        name="magaza_sipa_durum_b093ab_idx",
                    ),
                    models.Index(
                        fields=["bayi", "-olusturma_tarihi"],
                        name="magaza_sipa_bayi_id_98c80a_idx",
                    ),
                ],
            },
        ),
    ]
