# Generated by Django 5.2.17 on 2026-09-03 18:55

import apps.basvurular.models
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("katalog", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BasvuruDurumu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "olusturma_tarihi",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturma Tarihi"
                    ),
                ),
                (
                    "guncelleme_tarihi",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncelleme Tarihi"
                    ),
                ),
                (
                    "ad",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Durum Adı"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        max_length=120, unique=True, verbose_name="Kısa Ad"
                    ),
                ),
                (
                    "renk",
                    models.CharField(
                        default="#64748b",
                        help_text="Panelde rozet rengi. Örn: #16a34a",
                        max_length=7,
                        verbose_name="Renk",
                    ),
                ),
                (
                    "ikon",
                    models.CharField(
                        default="schedule", max_length=50, verbose_name="İkon"
                    ),
                ),
                (
                    "aciklama",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Açıklama"
                    ),
                ),
                (
                    "baslangic_durumu",
                    models.BooleanField(
                        default=False,
                        help_text="Yeni başvurular bu durumla açılır. Yalnızca bir durum işaretlenmelidir.",
                        verbose_name="Başlangıç Durumu",
                    ),
                ),
                (
                    "hakedis_tetikler",
                    models.BooleanField(
                        default=False,
                        help_text="Bu duruma geçildiğinde ücret kuralları işler ve cüzdan güncellenir.",
                        verbose_name="Para Hareketini Tetikler",
                    ),
                ),
                (
                    "olumsuz_sonuc",
                    models.BooleanField(
                        default=False,
                        help_text="İptal/hatalı gibi durumlar. Daha önce işlenmiş para hareketleri geri alınır.",
                        verbose_name="Olumsuz Sonuç",
                    ),
                ),
                (
                    "bayi_duzenleyebilir",
                    models.BooleanField(
                        default=False,
                        help_text="Eksik evrak gibi durumlarda bayinin başvuruyu güncellemesine izin verir.",
                        verbose_name="Bayi Düzenleyebilir",
                    ),
                ),
                (
                    "sinyal_seviyesi",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="Bayi panelinde 5 çubuklu sinyal göstergesinde kaç çubuk dolu görünsün (1-5).",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Sinyal Seviyesi",
                    ),
                ),
                ("sira", models.PositiveIntegerField(default=0, verbose_name="Sıra")),
                ("aktif", models.BooleanField(default=True, verbose_name="Aktif")),
            ],
            options={
                "verbose_name": "Başvuru Durumu",
                "verbose_name_plural": "2. Başvuru Durumları",
                "ordering": ["sira", "ad"],
            },
        ),
        migrations.CreateModel(
            name="Basvuru",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "olusturma_tarihi",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturma Tarihi"
                    ),
                ),
                (
                    "guncelleme_tarihi",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncelleme Tarihi"
                    ),
                ),
                (
                    "referans_no",
                    models.CharField(
                        default=apps.basvurular.models.referans_no_uret,
                        editable=False,
                        max_length=12,
                        unique=True,
                        verbose_name="Referans No",
                    ),
                ),
                (
                    "musteri_tipi",
                    models.CharField(
                        choices=[
                            ("turk", "Türk Vatandaşı"),
                            ("yabanci", "Yabancı Uyruklu"),
                            ("hepsi", "Her İkisi"),
                        ],
                        default="turk",
                        max_length=10,
                        verbose_name="Müşteri Tipi",
                    ),
                ),
                (
                    "kimlik_tipi",
                    models.CharField(
                        choices=[("tc", "T.C. Kimlik"), ("pasaport", "Pasaport")],
                        default="tc",
                        max_length=10,
                        verbose_name="Kimlik Tipi",
                    ),
                ),
                (
                    "kimlik_no",
                    models.CharField(
                        max_length=50, verbose_name="Kimlik / Pasaport No"
                    ),
                ),
                ("isim", models.CharField(max_length=100, verbose_name="İsim")),
                ("soyisim", models.CharField(max_length=100, verbose_name="Soyisim")),
                (
                    "irtibat",
                    models.CharField(max_length=20, verbose_name="İrtibat Numarası"),
                ),
                (
                    "numara",
                    models.CharField(
                        blank=True,
                        help_text="Taşıma ve şebeke içi işlemlerde doldurulur.",
                        max_length=20,
                        verbose_name="İşlem Yapılacak Numara",
                    ),
                ),
                ("adres", models.TextField(blank=True, verbose_name="Adres")),
                (
                    "ek_bilgiler",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Ek Bilgiler"
                    ),
                ),
                (
                    "bayi_aciklamasi",
                    models.TextField(blank=True, verbose_name="Bayi Açıklaması"),
                ),
                (
                    "operasyon_notu",
                    models.TextField(
                        blank=True,
                        help_text="Bayiye gösterilmez.",
                        verbose_name="Operasyon Notu",
                    ),
                ),
                (
                    "tahsil_edilen",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Tahsil Edilen",
                    ),
                ),
                (
                    "hakedis",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Hakediş",
                    ),
                ),
                (
                    "para_islendi",
                    models.BooleanField(
                        default=False, editable=False, verbose_name="Para İşlendi"
                    ),
                ),
                (
                    "sonuclanma_tarihi",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Sonuçlanma Tarihi"
                    ),
                ),
                (
                    "bayi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="basvurular",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Bayi",
                    ),
                ),
                (
                    "kampanya",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="basvurular",
                        to="katalog.kampanya",
                        verbose_name="Kampanya",
                    ),
                ),
                (
                    "kategori",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="basvurular",
                        to="katalog.basvurukategorisi",
                        verbose_name="Kategori",
                    ),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="basvurular",
                        to="katalog.operator",
                        verbose_name="Operatör",
                    ),
                ),
                (
                    "tarife",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="basvurular",
                        to="katalog.tarife",
                        verbose_name="Tarife",
                    ),
                ),
                (
                    "durum",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="basvurular",
                        to="basvurular.basvurudurumu",
                        verbose_name="Durum",
                    ),
                ),
            ],
            options={
                "verbose_name": "Başvuru",
                "verbose_name_plural": "1. Başvurular",
                "ordering": ["-olusturma_tarihi"],
            },
        ),
        migrations.CreateModel(
            name="DurumGecmisi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "aciklama",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Açıklama"
                    ),
                ),
                (
                    "tarih",
                    models.DateTimeField(auto_now_add=True, verbose_name="Tarih"),
                ),
                (
                    "basvuru",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="durum_gecmisi",
                        to="basvurular.basvuru",
                        verbose_name="Başvuru",
                    ),
                ),
                (
                    "degistiren",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="durum_degisiklikleri",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Değiştiren",
                    ),
                ),
                (
                    "onceki_durum",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="basvurular.basvurudurumu",
                        verbose_name="Önceki Durum",
                    ),
                ),
                (
                    "yeni_durum",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="basvurular.basvurudurumu",
                        verbose_name="Yeni Durum",
                    ),
                ),
            ],
            options={
                "verbose_name": "Durum Geçmişi",
                "verbose_name_plural": "Durum Geçmişi",
                "ordering": ["-tarih", "-id"],
            },
        ),
        migrations.CreateModel(
            name="BasvuruBelgesi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alan_kodu",
                    models.SlugField(max_length=60, verbose_name="Alan Kodu"),
                ),
                (
                    "etiket",
                    models.CharField(blank=True, max_length=150, verbose_name="Etiket"),
                ),
                (
                    "dosya",
                    models.FileField(upload_to="basvuru/%Y/%m/", verbose_name="Dosya"),
                ),
                (
                    "yuklenme_tarihi",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yüklenme Tarihi"
                    ),
                ),
                (
                    "basvuru",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="belgeler",
                        to="basvurular.basvuru",
                        verbose_name="Başvuru",
                    ),
                ),
            ],
            options={
                "verbose_name": "Başvuru Belgesi",
                "verbose_name_plural": "Başvuru Belgeleri",
                "ordering": ["basvuru", "alan_kodu"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("basvuru", "alan_kodu"),
                        name="basvuru_belge_alani_benzersiz",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="basvuru",
            index=models.Index(
                fields=["bayi", "-olusturma_tarihi"],
                name="basvurular__bayi_id_2c9b02_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="basvuru",
            index=models.Index(
                fields=["durum", "-olusturma_tarihi"],
                name="basvurular__durum_i_b63221_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="basvuru",
            index=models.Index(
                fields=["kategori", "-olusturma_tarihi"],
                name="basvurular__kategor_cbb223_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="basvuru",
            index=models.Index(
                fields=["kimlik_no"], name="basvurular__kimlik__84c17d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="basvuru",
            index=models.Index(fields=["numara"], name="basvurular__numara_c9218b_idx"),
        ),
    ]
