# Generated by Django 5.2.17 on 2026-09-03 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("basvurular", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="basvuru",
            name="irtibat",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="İrtibat Numarası"
            ),
        ),
        migrations.AlterField(
            model_name="basvuru",
            name="isim",
            field=models.CharField(blank=True, max_length=100, verbose_name="İsim"),
        ),
        migrations.AlterField(
            model_name="basvuru",
            name="kimlik_no",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Kimlik / Pasaport No"
            ),
        ),
        migrations.AlterField(
            model_name="basvuru",
            name="kimlik_tipi",
            field=models.CharField(
                blank=True,
                choices=[("tc", "T.C. Kimlik"), ("pasaport", "Pasaport")],
                default="tc",
                max_length=10,
                verbose_name="Kimlik Tipi",
            ),
        ),
        migrations.AlterField(
            model_name="basvuru",
            name="soyisim",
            field=models.CharField(blank=True, max_length=100, verbose_name="Soyisim"),
        ),
    ]
