# Generated by Django 5.2.17 on 2026-09-03 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("basvurular", "0002_alter_basvuru_irtibat_alter_basvuru_isim_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="basvurudurumu",
            name="bildirim_gonder",
            field=models.BooleanField(
                default=False,
                help_text="Bu duruma geçildiğinde operasyon grubuna mesaj atılır.",
                verbose_name="Telegram Bildirimi Gönder",
            ),
        ),
    ]
