# Generated by Django 5.2.17 on 2026-09-03 23:10

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("basvurular", "0003_basvurudurumu_bildirim_gonder"),
        ("katalog", "0005_kampanya_gorsel_tarife_gorsel_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="basvuru",
            name="tedarikci",
            field=models.ForeignKey(
                blank=True,
                help_text="İşlemi satın alan taraf. Boşsa işlem henüz satılmamıştır.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ustlendigi_basvurular",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Tedarikçi",
            ),
        ),
        migrations.AddField(
            model_name="basvuru",
            name="tedarikci_geliri",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=12,
                verbose_name="Tedarikçi Geliri",
            ),
        ),
        migrations.AddField(
            model_name="basvuru",
            name="tedarikci_islendi",
            field=models.BooleanField(
                default=False, editable=False, verbose_name="Tedarikçi Bedeli İşlendi"
            ),
        ),
        migrations.AlterField(
            model_name="basvuru",
            name="hakedis",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=12,
                verbose_name="Bayiye Hakediş",
            ),
        ),
        migrations.AlterField(
            model_name="basvuru",
            name="tahsil_edilen",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=12,
                verbose_name="Bayiden Tahsilat",
            ),
        ),
        migrations.AddIndex(
            model_name="basvuru",
            index=models.Index(
                fields=["tedarikci", "-olusturma_tarihi"],
                name="basvurular__tedarik_f1b759_idx",
            ),
        ),
    ]
