# Generated by Django 5.2.17 on 2026-09-03 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("basvurular", "0004_basvuru_tedarikci_basvuru_tedarikci_geliri_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="basvuru",
            name="belgeler_silindi",
            field=models.BooleanField(
                default=False,
                editable=False,
                help_text="Saklama süresi dolduğu için kimlik görüntüleri silindi.",
                verbose_name="Belgeler Silindi",
            ),
        ),
        migrations.AlterField(
            model_name="basvuru",
            name="sonuclanma_tarihi",
            field=models.DateTimeField(
                blank=True,
                help_text="Başvuru aktif ya da olumsuz bir duruma geçtiği an.",
                null=True,
                verbose_name="Sonuçlanma Tarihi",
            ),
        ),
    ]
