# Generated by Django 5.2.17 on 2026-09-03 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("basvurular", "0005_basvuru_belgeler_silindi_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="basvurudurumu",
            name="belgeleri_sil",
            field=models.BooleanField(
                default=False,
                help_text="Bu duruma geçildiğinde kimlik ve pasaport görüntüleri hemen silinir. İşi biten başvurularda açın; sonradan düzeltme ihtimali olan durumlarda (Hatalı, Eksik Evrak) kapalı bırakın.",
                verbose_name="Belgeleri Sil",
            ),
        ),
        migrations.AlterField(
            model_name="basvuru",
            name="belgeler_silindi",
            field=models.BooleanField(
                default=False,
                editable=False,
                help_text="İşi bittiği için kimlik görüntüleri silindi.",
                verbose_name="Belgeler Silindi",
            ),
        ),
    ]
