# Generated by Django 5.2.17 on 2026-09-04 06:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("basvurular", "0006_basvurudurumu_belgeleri_sil_and_more"),
        ("katalog", "0006_basvurukategorisi_sim_karsiligi_gerekir"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="basvuru",
            name="sim_karsiligi_alindi",
            field=models.BooleanField(
                default=False,
                help_text="Bu aktivasyonun tükettiği SIM'in yenisi operatörden alındı mı?",
                verbose_name="SIM Karşılığı Alındı",
            ),
        ),
        migrations.AddField(
            model_name="basvuru",
            name="sim_karsiligi_tarihi",
            field=models.DateTimeField(
                blank=True,
                editable=False,
                null=True,
                verbose_name="SIM Karşılığı Alınma Tarihi",
            ),
        ),
        migrations.AddIndex(
            model_name="basvuru",
            index=models.Index(
                fields=["sim_karsiligi_alindi", "-olusturma_tarihi"],
                name="basvurular__sim_kar_8d4b4e_idx",
            ),
        ),
    ]
