# Generated by Django 5.2.17 on 2026-09-04 07:39

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("basvurular", "0007_basvuru_sim_karsiligi_alindi_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="basvuru", name="tedarikci_geliri",),
        migrations.RemoveField(model_name="basvuru", name="tedarikci_islendi",),
        migrations.AddField(
            model_name="basvuru",
            name="ana_hakedis",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Operatörden ya da işlemi üstlenen tedarikçiden aldığımız tutar.",
                max_digits=12,
                verbose_name="Ana Hakediş",
            ),
        ),
        migrations.AddField(
            model_name="basvuru",
            name="ana_hakedis_islendi",
            field=models.BooleanField(
                default=False, editable=False, verbose_name="Ana Hakediş İşlendi"
            ),
        ),
    ]
