# Generated by Django 5.2.17 on 2026-09-04 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("basvurular", "0008_remove_basvuru_tedarikci_geliri_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="basvuru", name="kampanya",),
    ]
