# Generated by Django 5.2.17 on 2026-09-05 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("basvurular", "0009_remove_basvuru_kampanya"),
    ]

    operations = [
        migrations.AddField(
            model_name="basvuru",
            name="para_surumu",
            field=models.PositiveIntegerField(
                default=0,
                editable=False,
                help_text="Para her geri alındığında artar. Defterdeki tekillik anahtarı bu sayıyı içerir; yanlışlıkla onaylanan başvuru geri alınıp yeniden işlenebilsin diye.",
                verbose_name="Para İşlem Sürümü",
            ),
        ),
    ]
