# Generated by Django 5.2.17 on 2026-09-05 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("basvurular", "0010_basvuru_para_surumu"),
        ("katalog", "0008_kampanya"),
    ]

    operations = [
        migrations.AddField(
            model_name="basvuru",
            name="kampanya",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="basvurular",
                to="katalog.kampanya",
                verbose_name="Kampanya",
            ),
        ),
    ]
