# Generated by Django 5.2.17 on 2026-09-05 09:24

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("basvurular", "0011_basvuru_kampanya"),
    ]

    operations = [
        migrations.AddField(
            model_name="basvuru",
            name="giris_bedeli",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Başvuru girilirken bayiden tahsil edilen tutar. Başlangıç durumuna yazılmış tahsilat kuralından gelir.",
                max_digits=12,
                verbose_name="Giriş Bedeli",
            ),
        ),
        migrations.AddField(
            model_name="basvuru",
            name="giris_bedeli_islendi",
            field=models.BooleanField(
                default=False, editable=False, verbose_name="Giriş Bedeli İşlendi"
            ),
        ),
    ]
