# Generated by Django 5.2.17 on 2026-09-05 15:05

from django.db import migrations, models


def durumlari_tedarikciye_ac(apps, schema_editor):
    """Kurulu sistemlerde başlangıç dışındaki durumları tedarikçiye açar.

    Alan boş (False) gelseydi tedarikçi ekranındaki kutu hiç çizilmez,
    özellik ancak yönetici yedi durumu tek tek işaretleyince görünür
    olurdu — kimse aramadığı bir kutuyu bulamaz. Kategori alanlarındaki
    kural burada da geçerli: kapatmak eklemekten kolaydır.

    Başlangıç durumu dışarıda kalır; başvuruyu kuyruğun başına geri atmak
    tedarikçinin işi değil.
    """
    BasvuruDurumu = apps.get_model("basvurular", "BasvuruDurumu")
    BasvuruDurumu.objects.filter(baslangic_durumu=False).update(tedarikci_secebilir=True)


class Migration(migrations.Migration):

    dependencies = [
        ("basvurular", "0012_basvuru_giris_bedeli_basvuru_giris_bedeli_islendi"),
    ]

    operations = [
        migrations.AddField(
            model_name="basvurudurumu",
            name="tedarikci_secebilir",
            field=models.BooleanField(
                default=False,
                help_text="İşlemi üstlenen tedarikçi başvuruyu bu duruma çekebilir. Aktivasyonu fiilen tedarikçi yaptığı için sonucu da o bildirir.",
                verbose_name="Tedarikçi Seçebilir",
            ),
        ),
        migrations.RunPython(durumlari_tedarikciye_ac, migrations.RunPython.noop),
    ]
