# Generated by Django 5.2.17 on 2026-09-05 19:14

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("basvurular", "0013_basvurudurumu_tedarikci_secebilir"),
    ]

    operations = [
        migrations.AlterField(
            model_name="basvuru",
            name="ana_hakedis",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Bu işlem için operatöre ya da işlemi üstlenen tedarikçiye ödediğimiz tutar. Kâr hesabında giderdir.",
                max_digits=12,
                verbose_name="Alış Bedeli",
            ),
        ),
    ]
