# Generated by Django 5.2.17 on 2026-09-05 20:39

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("basvurular", "0014_alter_basvuru_ana_hakedis"),
    ]

    operations = [
        migrations.RenameField(
            model_name="basvuru", old_name="ana_hakedis", new_name="alis_bedeli",
        ),
        # Sil + ekle DEĞİL, yeniden adlandırma: bayrak silinseydi işlenmiş
        # başvurular "para işlenmemiş" görünür ve bir sonraki durum
        # değişiminde aynı para ikinci kez işlenirdi.
        migrations.RenameField(
            model_name="basvuru",
            old_name="ana_hakedis_islendi",
            new_name="alis_bedeli_islendi",
        ),
        migrations.AddField(
            model_name="basvuru",
            name="alinan_prim",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Bu işlem için operatörün ya da tedarikçinin bize ödediği prim. Kâr hesabında gelirdir. Maliyetle aynı anda olabilir: hattı satın alıp aktivasyon için ayrıca prim de alabiliriz.",
                max_digits=12,
                verbose_name="Alınan Prim",
            ),
        ),
        migrations.AddField(
            model_name="basvuru",
            name="alinan_prim_islendi",
            field=models.BooleanField(
                default=False, editable=False, verbose_name="Alınan Prim İşlendi"
            ),
        ),
        migrations.AlterField(
            model_name="basvuru",
            name="alis_bedeli_islendi",
            field=models.BooleanField(
                default=False, editable=False, verbose_name="Alış Bedeli İşlendi"
            ),
        ),
    ]
