# Generated by Django 5.2.17 on 2026-09-25 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("basvurular", "0016_durum_bildirimlerini_kapat"),
    ]

    operations = [
        migrations.AddField(
            model_name="basvuru",
            name="aktif_numara",
            field=models.CharField(
                blank=True,
                help_text="Aktivasyonda hatta verilen numara. Bayi başvurusunun en üstünde görür. 0532 123 45 67 gibi yazılabilir; tek biçime çevrilir.",
                max_length=20,
                verbose_name="Aktif Edilen Numara",
            ),
        ),
    ]
